### ISSUE TITLE
Product special prices are not syncing 

### ISSUE THREAD

**Issue by magixrys** [facebookincubator/Facebook-For-OpenCart#84] opened 2019-01-01 23:55 UTC
When I bulk edit product prices, the new prices are not syncing to facebook catalog, so my customers cannot see the discounted products. Is there any solution for this?
I run the latest version of facebook for opencart 2.3.0.2 with 1000+ products and except from the above issue I see that the extension cannot synchronize the catalog. It says that last successful update was on June. However I can see the products on my facebook store. Is there a way to fix these? I want to start using the extension for advertizing, but I am not sure everything will be ok.

**Comment by shue249** [comment] 2019-01-05 03:30
@magixrys Thank you for your feedback. Can we understand how are you performing the bulk edit? Are you using any 3rd party extensions?

Our plugin integrated with the default OpenCart product management module, such that every product changes made from the product management module (add, edit, delete) will sync the changes to Facebook catalog.

**Comment by magixrys** [comment] 2019-01-05 10:52
Yes, I am using a 3rd party extension for bulk editing products (Product manager by isense labs). And I see that products that had been bulk edited have wrong price on my facebook store. I started advertizing products from my facebook catalog, but first I had to edit product prices one by one. Is there a solution to this? Editing each product's price is very time consuming when having to edit 1000+ products.

**Comment by shue249** [comment] 2019-01-10 00:58
@magixrys Let us evaluate for possible solution for this.

**Comment by nasspar** [comment] 2019-01-24 00:00
Hello,
i have the same problem. I'm using an external software - eMagicOne Store manager. I'm not sure that its the reason.. so far i tried several methods of sync discount prices - but no change, even when i use default method. Before installing your plugin i have already added the discounts. After installing the extension and map them - price map to sale_price in settings options of fb catalog - they appear correctly. When i edit the price using both method - default via opencart admin tab or external bridge connected software - and fetch the data again - no change in the price - every time it takes the first added price when the catalog is created. I'm not sure that is from any 3rd part plugin...
So i create a whole new product and add special price to it via the default admin. After fetching the new data - the price is without the discount. So in my opinion the problem is in the update function (fetching update data from facebook) When we create for first time the catalog it correspond correctly, but after every next update no detection in price modification. The issue is only for prices.
Could you please check what could be the problem?

Also the initiate checkout does not fire the event in facebook - doesnt work. Could you please correct that too. :))
Thanks

**Comment by shue249** [comment] 2019-02-03 01:34
@nasspar For the initiate checkout issue, are you using the SEO editor plugin? If so, can you look at this post and see if it helps you https://github.com/facebookincubator/Facebook-For-OpenCart/issues/82

**Comment by mupcku** [comment] 2019-04-08 10:44
im NOT using 3rd party module, and im just updating 9 of my products with special prices. The prices are updating as well and im able to see the changes in the catalog, BUT when i create campaign and i want to customize the images, so i can show the new and the old price i getting the following error: "The catalog info for *my product" exceeds our character limit so it won't show in your ad. You can edit this info in your catalog."

**Comment by shue249** [comment] 2019-04-08 15:52
@mupcku Will you be able to help us to follow up by creating a new ticket.

Can you check the character length of name and description of the product. We have a character limit on the lengths.
https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog#required-fields

![image](https://user-images.githubusercontent.com/11957585/55738264-a60b9e80-59db-11e9-9698-40d8cda30e2c.png)

**Comment by shue249** [comment] 2019-06-04 06:16
@magixrys We have released a new version of the plugin - 2.1.10. We greatly improved the performance of the Resync products feature in Facebook Business Extension module. You can use this function to re-sync your products from Opencart to facebook catalog at one go, after you made all the bulk edits to your products using the 3rd party plugin. The catalog will remain the same.

We will be closing out the ticket, feel free to reach to us if you have any further questions.

**Closed by shue249** 2019-06-04 06:16 UTC
Labels: 3rd party catalog extension
