### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by awadi13** [facebookincubator/Facebook-For-OpenCart#14] opened 2018-06-29 22:27 UTC
1- if i go to facebook button will take me to 
 " page isn’t working 
is currently unable to handle this request.
HTTP ERROR 500 "
2- if i go to extension < module  < facebook < no permission  
even i gave the permission to wright and read 

my opencart is 2.3.0.2
i installed v2.0.2
please help

**Comment by shue249** [comment] 2018-07-01 00:28
Thank you for your feedback and patience!

As the problem is too generic for us to debug here, we will need more details to be able to proceed. Will you be able to access the facebook button again and then share with us your web server log file at ads_extension_opencart@fb.com?

**Comment by awadi13** [comment] 2018-07-01 12:48
i can't access the facebook button and even my admin 
i had to uninstall it to access the admin again

**Comment by awadi13** [comment] 2018-07-01 12:49
Montajaat.com<http://Montajaat.com>



On 1 Jul 2018, at 3:28 AM, shue249 <notifications@github.com> wrote:


Thank you for your feedback and patience!

As the problem is too generic for us to debug here, we will need more details to be able to proceed. Will you be able to access the facebook button again and then share with us your web server log file at ads_extension_opencart@fb.com<mailto:ads_extension_opencart@fb.com>?

**Comment by awadi13** [comment] 2018-07-05 13:46
u mean log of my panel ?!
if yes where should i send the details ?!

**Comment by shue249** [comment] 2018-07-06 16:08
Hi! Can you send the log file to ads_extension_opencart@fb.com

**Comment by awadi13** [comment] 2018-07-10 12:18
hi dear 
i already sent the file, is there any update ?
thank you

**Comment by shue249** [comment] 2018-07-12 05:56
@awadi13 Our email system filtered away attachments, so your email came in with no log file. Is there anyway you can host the file on a public location for us to test?

**Comment by shue249** [comment] 2018-07-12 23:38
@awadi13 We looked at some of your logs on Facebook side. I believe that you are using our plugin version of 2.0.0. Can you uninstall/remove this version and install the newer version of 2.0.2 - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.0.2. 

Let us know if this works for you.

**Comment by awadi13** [comment] 2018-07-13 17:07
i am using the 2.0.2 
even i installed the 2.0.2 again but still same issue, i can't reach the facebook button page

**Comment by shue249** [comment] 2018-07-29 01:42
@awadi13 Closing this case as the bug has been resolved in the 2.0.2 version of our plugin. Feel free to re-open if you are still encountering any problems.

**Closed by shue249** 2018-07-29 01:42 UTC
Labels: bug
