### ISSUE TITLE
Pixel not found - Opencart 3.0.2.0 with journal theme 2.16.8

### ISSUE THREAD

**Issue by Superstar18** [facebookincubator/Facebook-For-OpenCart#183] opened 2019-05-31 10:41 UTC
Hi,

i think the last 2 versions have a problem because the pixel can't be found on my store after installing them.
I had to go back to a earlier version i found here and the pixel works fine again: https://www.facebook.com/business/help/1494437460610744

I'm using opencart 3.0.2.0 with journal theme 2.16.8

**Comment by shue249** [comment] 2019-05-31 12:18
@Superstar18 
1. We have just launched a version 2.1.9, does that work?

2. What is your website URL?

3. Can you share this file from your webserver to here?
![image](https://user-images.githubusercontent.com/11957585/58705279-47621000-83e1-11e9-87b0-a07817b60b95.png)

**Comment by Superstar18** [comment] 2019-05-31 13:53
Hi,

I tried the version launched today and the one launched a few weeks ago. Both had the same problem.
The pixel can't be found.

The website url is iconicul.ro
Is there a way i can send that file in private?

Thank you!

**Comment by shue249** [comment] 2019-05-31 21:47
@Superstar18 You can send the file to our email alias - ads_extension_opencart@fb.com. Pls also indicate your github user id so that we have the context when responding to you.

**Comment by shue249** [comment] 2019-05-31 21:51
@Superstar18 Can you also install in the version 2.1.9 on your website so that we can understand where is the problem.

**Comment by Superstar18** [comment] 2019-06-01 08:37
Hi,

I sent the file by e-mail.

Thank you!

**Comment by shue249** [comment] 2019-06-02 19:49
@Superstar18 We received your files and we found that there are no changes to the 2 files, which should not be the case, as we expect that there should be at least 1 change. Can we check if you pressed on the Refresh modifications button?
![image](https://user-images.githubusercontent.com/11957585/58766546-e0ee0680-8534-11e9-9008-8e24f8c23862.png)

**Comment by RuDee-BG** [comment] 2019-06-03 07:48
Hello, i have the same problem, Facebook Ad managers is ALL green, but facebook helper shows no pixel found, we using OC 3.0.2.0 and Journal 2 theme, when i first installed Facebook Ad manager it works until i update to the last version?

**Comment by Superstar18** [comment] 2019-06-03 11:58
@shue249 Ok, i'll send them again now.

**Comment by shue249** [comment] 2019-06-03 15:05
@RuDee-BG Can you share the details from this earlier comment https://github.com/facebookincubator/Facebook-For-OpenCart/issues/183#issuecomment-497688460

**Comment by shue249** [comment] 2019-06-03 15:08
@Superstar18 We received your latest files. Can you try another approach. Clear the log from modifications, then install 2.1.9 and refresh modifications and share with us the log file.
![image](https://user-images.githubusercontent.com/11957585/58812436-beacc500-85d6-11e9-994d-926cde0d9b54.png)

**Comment by RuDee-BG** [comment] 2019-06-03 15:09
What you'll need more as details?

**Comment by RuDee-BG** [comment] 2019-06-03 15:18
climatshop.bg 
[router.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3248292/router.zip)

**Comment by shue249** [comment] 2019-06-03 15:27
@RuDee-BG Thanks for the file, we know where the root cause of your problem is, we will be releasing a fix soon

**Comment by Superstar18** [comment] 2019-06-03 16:31
@shue249 I sent it again like you said.

**Comment by shue249** [comment] 2019-06-03 17:17
@Superstar18 There is something that we are unable to understand from your file.

If you look at the file provided by @RuDee-BG , this is what we expected and we have the fix for his case. However, your file is missing that section, which means something else is going on in your system and we are unsure what is the reason.

![image](https://user-images.githubusercontent.com/11957585/58820900-b52c5880-85e8-11e9-8a43-f1bb337151ef.png)

**Comment by Superstar18** [comment] 2019-06-03 17:32
I don't understand why. I sent the file again. I hope now's ok.

**Comment by shue249** [comment] 2019-06-03 17:37
@Superstar18 There is another thing. Can you check if you have disabled the cache - https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

After that, refresh the modifications and send us the router.php file again.

**Comment by Superstar18** [comment] 2019-06-03 18:48
Done. I sent it again...

**Comment by RuDee-BG** [comment] 2019-06-04 05:10
Just for the info, my cache in journal theme options is off, i have other issues with it and i keep it disabled.

**Comment by shue249** [comment] 2019-06-04 05:53
@RuDee-BG , @Superstar18  We have just released a version 2.1.10 of the plugin, which attempts to solve your pixel problem. Can you try out this update and let us know if the issue is resolved.

@Superstar18 We do not have confidence that the update may solve your problem as we do not see the expected root cause on your router.php. But, still give it a try and let us know.

**Comment by RuDee-BG** [comment] 2019-06-04 05:59
After update my site is broken totaly: 

Fatal error: Cannot redeclare Router::runAction() in /home/climatshopbg/ocartdata/storage/modification/system/engine/router.php on line 30

**Comment by shue249** [comment] 2019-06-04 06:11
@RuDee-BG Can you share your router file here

**Comment by RuDee-BG** [comment] 2019-06-04 06:15
[router10.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3250790/router10.zip)

**Comment by shue249** [comment] 2019-06-04 06:19
@RuDee-BG Can you also share the original router.php file that you have in this folder? I may have some idea on why your system is broken.

![image](https://user-images.githubusercontent.com/11957585/58855902-0de60a80-8656-11e9-980c-a5b945c2bc96.png)

**Comment by RuDee-BG** [comment] 2019-06-04 06:21
[router0.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3250813/router0.zip)

**Comment by shue249** [comment] 2019-06-04 06:25
@RuDee-BG Can you remove the extension, click the Refresh modifications button. Then install and click on Refresh modifications button again

**Comment by RuDee-BG** [comment] 2019-06-04 06:28
I did it, and its working now. Now Facebook pixel helper found the pixel. Thank you for the fast fix!

**Comment by shue249** [comment] 2019-06-04 06:28
@RuDee-BG Great to hear that its working now!

**Comment by Superstar18** [comment] 2019-06-04 06:36
Hi,
I installed it now and it seems to work fine, thank you.
It's installing under another module "facebook business extension" instead of "facebook ads extension" and that's why we get error 500.  I removed "facebook ads extension" and worked fine after.

Thank you!
Marius

**Comment by Superstar18** [comment] 2019-06-04 07:41
Hi @shue249 ,

I don't understand how but all my opencart is broken. All the tables are chaos.
I recommend you to don't let everybody install the update till it's stabile.

**Comment by shue249** [comment] 2019-06-04 14:12
@Superstar18 Are you getting HTTP 500 error on your website? We have the steps on how to fix it - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/189

You will need to remove the older versions of the plugin and install the newer version.

**Comment by Superstar18** [comment] 2019-06-04 14:18
@shue249 That was the initial problem and was solved when i disabled the old module.
In this process, the initial opencart template was erased and we added it again and the problem was solved. Not sure but i think installing the new FB module or deleting the old one somehow caused this.

**Comment by shue249** [comment] 2019-06-04 14:25
@Superstar18 Just to clarify, are you still having problems on your OpenCart? If you manage to delete the old version away and install just the new version and click on Refresh modifications, it should be fine.

If you are still having problems, can you share with me the errors shown.

**Comment by Superstar18** [comment] 2019-06-04 14:34
@shue249 We solved the errors. After deleting the old module and installing the new one, the initial opencart template was erased as well. We added it back and works fine but i wanted to tell you about this, just as a info.
Everything works fine now. Thank you for your assistance.

**Comment by shue249** [comment] 2019-06-04 16:34
@Superstar18 Glad that this works. Can I also confirm with you that the pixel firing is also working on your website now.

**Comment by Superstar18** [comment] 2019-06-05 21:56
Hi @shue249,
I think there is still a problem. I see that the pixel is appearing only after i click "allow cookies" button.
Is this right? I know that GDPR doesn't tell us to do that. By continuing the client accepts automatically the terms and conditions.

**Comment by Superstar18** [comment] 2019-06-05 22:00
I disabled it for now so we will not have a problem with the pixel but if you need me to activate it to see what's happening, let me know.

**Comment by shue249** [comment] 2019-06-06 07:12
@Superstar18 The pixel will continue to fire as long as the user does not answer the cookie bar. The moment the user selects any option in the cookie bar, we will use the option to decide whether to fire the pixel.

You can try this out on a fresh copy of Chrome with all data cache removed (so that the cookie bar selection is cleared) and then check on pixelhelper.

**Comment by shue249** [comment] 2019-06-07 15:57
We will be closing out this ticket. Feel free to reach to us if you have any further questions.

**Closed by shue249** 2019-06-07 15:57 UTC

**Comment by Superstar18** [comment] 2020-09-12 06:32
Hi @shue249 

It seems that after a update, we have a new problem,

After installing the module and setting it up, the website is working find except when we try to access the checkout or cart page.. You can see a screenshot here:
https://prnt.sc/uej7tj

After i uninstalled the settings, everything is working fine again.

Could you please check? I saw there are also 2 people that have the same issue but they added the report 9 days ago so that's a very long time to not have the pixel set up. I hope you will consider my report as fast as possible so we could find a solution.

This issue is happeing on all browsers i checked. Also checked from other devices.
I've installed the module corectly, refreshed modifications and so on.

Thank you!
Marius
