### ISSUE TITLE
Messenger Chat not Appearing

### ISSUE THREAD

**Issue by iq860** [facebookincubator/Facebook-For-OpenCart#167] opened 2019-05-12 17:26 UTC
Messenger chat bubble not appearing on the website even after several reinstalls and cash clearing. I can see the activity on my pixel and its reading events from my site.

Plugin Version: 2.1.8
Opencart Version: 3.0.2.0
Website: [el-vet.com](https://el-vet.com)
Theme: Default

**Comment by shue249** [comment] 2019-05-12 23:46
@iq860 Thank you for the feedback.

Can you copy out these 2 files from your webserver and share here for us to better dig into the possible root causes.
![image](https://user-images.githubusercontent.com/11957585/57589182-02218f80-7553-11e9-86cc-3fb2247e2ff7.png)
![image](https://user-images.githubusercontent.com/11957585/57589192-267d6c00-7553-11e9-88e2-84daa555bd7d.png)

**Comment by iq860** [comment] 2019-05-13 03:38
@shue249 sure here you go
[footer.php](https://drive.google.com/open?id=1oo33VWHfsE0Y-ldQCH0aLylb03LJ9m0O)
[footer.twig](https://drive.google.com/open?id=1oKgfjEH3S-DSP-UDKgSc-Q-ZJHzjvS4N)

and thanx for your quick response

**Comment by shue249** [comment] 2019-05-13 04:47
@iq860 From your files, the plugin modifications are correct. We have 1 more place to check. Will you be able to download the plugin log file and share the log file with us here?

**Comment by iq860** [comment] 2019-05-13 04:48
@shue249 can you define its location?

**Comment by iq860** [comment] 2019-05-14 18:55
@shue249 can you tell me the location for the log files that you need? I'll share them right away, thnx

**Comment by shue249** [comment] 2019-05-15 00:01
@iq860 
![image](https://user-images.githubusercontent.com/11957585/57739801-93296f80-76e7-11e9-95d3-015220bf8403.png)

**Comment by shue249** [comment] 2019-05-15 00:14
@iq860 One more suggestion. Can you disable the theme cache and see if the messenger chat plugin can now be shown. A screenshot is here - https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

**Comment by iq860** [comment] 2019-05-15 04:40
@shue249 I already have theme cash disabled and I just did a refresh for it, sadly still not working.
here is the log filr
[el-vet_2019-05-15_06-38-07_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3180934/el-vet_2019-05-15_06-38-07_facebook_ads_extension.log)

**Comment by shue249** [comment] 2019-05-16 15:13
@iq860 After checking the files and settings, I couldnt figure out why the messenger chat plugin failed to load on your website.

Are you using vqmod?

**Comment by shue249** [comment] 2019-05-18 02:45
@iq860 We have 1 more idea to share.

Can you try to disable the SASS cache too.

![image](https://user-images.githubusercontent.com/11957585/57963653-0afed080-795a-11e9-85a4-9225cc931b1f.png)

**Comment by iq860** [comment] 2019-05-19 07:20
> @iq860 After checking the files and settings, I couldnt figure out why the messenger chat plugin failed to load on your website.
> 
> 1. Are you using vqmod?
> 2. Are you using any plugins which amend the footer?

@shue249 Thanx so much for the help !! I did have an edit at Theme Editor for the footer
when I removed the edit the plugin worked gr8! thanx for `that!`

btw here is my footer edit 
[footer.txt](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3194853/footer.txt)

**Comment by shue249** [comment] 2019-05-19 08:19
@iq860 Great to hear that it is working.

Can we understand what is the edit that you made, so that we can think on how to further improve our plugin.

**Comment by iq860** [comment] 2019-05-20 05:42
@shue249
ANY edit at all at the footer will render the messenger plugin to be broken.
**Even just viewing the footer.twig without edits and saving it to the theme editor will break messenger.**

my edit was removing "Powered By OpenCart" text and link

![footer](https://user-images.githubusercontent.com/15311677/57998618-555f8900-7ae3-11e9-993a-1a7f6b7ea59a.PNG)

**Comment by shue249** [comment] 2019-05-31 02:11
@iq860 We have released a new version 2.1.9 which moved the messenger chat plugin from footer to header. This means that you can make edits to the footer via Theme Editor and our plugin will still be able to show the Messenger chat plugin.

We will be closing out this ticket, feel free to reach to us if you have any comments.

**Closed by shue249** 2019-05-31 02:11 UTC

**Comment by patikas14** [comment] 2020-12-06 17:29
Hello guys.

I'm in the same situation...
Can you please help me too @shue249 ?

Did everything i saw here, but no luck.
I'm also using Journal (3.1.4) and opencart 3.0.3.2

I use the latest Facebook plugin.

I cant find a solution!
I attach the log file [here](https://drive.google.com/open?id=15zh3_FjDyZyu-ZzSsJYx2dk4t-KjFmUV) if you need it.

If you want me to share anything, let me know...
