### ISSUE TITLE
404 =model&token problem

### ISSUE THREAD

**Issue by filipburman** [facebookincubator/Facebook-For-OpenCart#307] opened 2019-12-09 14:41 UTC
Hi,
We have a problem getting the module to work with our checkout and ajax filter.
For some reason the front.php file is causing problem with our site. Both filter module and checkout. We get a 404 error in the console reacting to a FB token access.

"b'coz I found that in system/engine/front.php file they are added code using their OCMOD file and that changes will not work in our site.
"
"If I remove front.php file override changes by the OCMOD then our site is working fine "

Any idea?
![Screen Shot 2019-12-09 at 15 38 20](https://user-images.githubusercontent.com/9830505/70444523-4e599180-1a9a-11ea-9328-46bc43df370f.png)

**Comment by shue249** [comment] 2019-12-10 03:24
@filipburman Thank you for sharing this feedback.

Yes, our plugin is making changes to the front.php with some code for the Facebook pixel firing on the web store. However, we are not directly calling any URL in the form of extension/extension shown on your javascript console.

We are curious to understand a few things
1. The latest version of the plugin is 2.2.0. Are you using this version? https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.0

2. The installation of our plugin is shown on these 2 videos. Do you also use the same method to install the plugin? https://drive.google.com/open?id=1V4Nu8nlmHX5ppKqsjcR-xR05Rozb7MKN, https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum

3. Have you made any direct changes to the plugin codes on your local server?

4. Will you be able to share a copy of the modified front.php here for us to take a look?

**Comment by nlwebdev** [comment] 2019-12-10 07:16
Hi,

Myself Ashvin. 

The latest version of the plugin is 2.2.0. Are you using this version? https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.0
-- Yes we are using latest version. See attached screenshot
![image](https://user-images.githubusercontent.com/40201928/70503791-35a8b480-1b4a-11ea-8e36-8de509178ddb.png)


The installation of our plugin is shown on these 2 videos. Do you also use the same method to install the plugin? https://drive.google.com/open?id=1V4Nu8nlmHX5ppKqsjcR-xR05Rozb7MKN, https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum
-- yes we used same method to install plugin
 
Have you made any direct changes to the plugin codes on your local server?
-- No we didn't change anything in plugin's files

Will you be able to share a copy of the modified front.php here for us to take a look?
-- yes please check zip file of front.php file
[front.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3943453/front.zip)


If I removed override code of facebook plugins in front.php file then site loads perfectly fine and no any ajax calling URL called which we sent you earlier.

Waiting for your positive response.

Thanks,
Ashvin

**Comment by shue249** [comment] 2019-12-16 04:10
@nlwebdev Ashvin, we looked at your version front.php and found that this is the same as our front.php after installing the plugin. Based on the current data we have, we are unable to further determine what could be the root cause.

Do you have development resources that can continue to investigate the problem? Some suggestions we have:
1. Do you change the admin folder name?

2. The error you shown on the screenshot is coming from the web front end, where the browser is making a call to the server endpoint on extension/extension. Are you able to trace which part of the code is making this call.

3. We have a class called FacebookEventParameters which is preparing the pixel information. You may want to take a look at this code pointer to see it could be of any help. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L127

**Comment by shue249** [comment] 2020-01-02 02:00
@nlwebdev Wondering if you have any further updates to this issue.

**Comment by shue249** [comment] 2020-01-20 00:12
@nlwebdev We will be closing out this ticket for now. But, pls feel free to reach to us if you have any further questions or updates.

**Closed by shue249** 2020-01-20 00:12 UTC
