### ISSUE TITLE
Issues with install

### ISSUE THREAD

**Issue by Steve-Regal** [facebookincubator/Facebook-For-OpenCart#276] opened 2019-10-14 14:52 UTC
Good afternoon,

Have 3 domains all running with Facebook Pixel and Facebook Messenger:

www.regalautosport.com/shop (OC 2.0.2.0 with Journal 2 theme)
www.csfrace.eu (OC 2.1.0.2 with Journal 2 theme)
www.wavetrac.eu (OC 2.1.0.2 with Journal Theme)

All 3 domains have been setup the same and have VQmod and the 'Quickfix' for FTP bypass. When i originally loaded the Facebook extension it said that there was an issue with a missing database table. 

I went through all of the usual bug fix's suggested by the internet, made sure all of the files where given 'ReadWriteExecute' permissions etc. 

Tried loading the upload files by FTP (Filezilla) and it would not load the extension. Also the 'modules' tab in the website admin area failed to load with 'Page not found'. Then i tried to upload a .zip file through the extension installer and this caused my Journal theme to fail. Nothing will load on the site. There is a 'module' folder with a Facebook file in the root /catalog/controller/extension and if i remove this file my Journal theme works again.

**Comment by shue249** [comment] 2019-10-15 08:56
@Steve-Regal 
1. For the missing database table, it is because we need to create a new table on your database. You will need to grant the CREATE and ALTER table permissions for the MYSQL database user. 

2. For the module folder, is it affecting for only 2.0.2.0? Because this is a known problem for older versions. And it is ok to remove away the module folder.

**Comment by Steve-Regal** [comment] 2019-10-16 09:46
HI,

Am now getting this:

SyntaxError: JSON Parse error: Unrecognized token '<'
parsererror
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
<meta charset="UTF-8" />
<title>Page Not Found!</title>
<base href="https://www.regalautosport.com/shop/admin/" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
<script type="text/javascript" src="view/javascript/jquery/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="view/javascript/bootstrap/js/bootstrap.min.js"></script>
<link href="view/javascript/bootstrap/opencart/opencart.css" type="text/css" rel="stylesheet" />
<link href="view/javascript/font-awesome/css/font-awesome.min.css" type="text/css" rel="stylesheet" />
<link href="view/javascript/summernote/summernote.css" rel="stylesheet" />
<script type="text/javascript" src="view/javascript/summernote/summernote.js"></script>
<script src="view/javascript/jquery/datetimepicker/moment.js" type="text/javascript"></script>
<script src="view/javascript/jquery/datetimepicker/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<link href="view/javascript/jquery/datetimepicker/bootstrap-datetimepicker.min.css" type="text/css" rel="stylesheet" media="screen" />
<link type="text/css" href="view/stylesheet/stylesheet.css" rel="stylesheet" media="screen" />
<script src="view/javascript/common.js" type="text/javascript"></script>
</head>
<body>
<div id="container">
<header id="header" class="navbar navbar-static-top">
  <div class="navbar-header">
        <a type="button" id="button-menu" class="pull-left"><i class="fa fa-indent fa-lg"></i></a>
        <a href="https://www.regalautosport.com/shop/admin/index.php?route=common/dashboard&amp;token=877c62999750025c063f1a514a5bc05f" class="navbar-brand"><img src="view/image/logo.png" alt="OpenCart" title="OpenCart" /></a></div>
    <ul class="nav pull-right">
    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"><span class="label

If i upload via .zip i get the following when refreshing the modules:

Warning: DOMDocument::loadXML(): CData section not finished <!-- DO NOT MODIFY, use for indicating pi in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag add line 1357 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag operation line 1355 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag file line 1354 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag modification line 9 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Notice: Trying to get property of non-object in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 142

and this causes the website to crash

**Comment by Steve-Regal** [comment] 2019-10-16 09:46
Warning: DOMDocument::loadXML(): CData section not finished <!-- DO NOT MODIFY, use for indicating pi in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag add line 1357 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag operation line 1355 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag file line 1354 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Warning: DOMDocument::loadXML(): Premature end of data in tag modification line 9 in Entity, line: 1483 in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 139Notice: Trying to get property of non-object in /home/regalautosport/public_html/shop/admin/controller/extension/modification.php on line 142

**Comment by shue249** [comment] 2019-10-20 13:18
@Steve-Regal Can I check if you have renamed away the admin folder into a different name?

**Comment by shue249** [comment] 2019-10-20 13:24
@Steve-Regal Can you uninstall and remove away our plugin from your webserver and then try to install back the plugin and click on refresh modifications.

The problem is most likely due to the older version of OpenCart where the modification database table is having a small data size for the xml field, resulting in truncation errors when there are too many modifications installed. We have put in this fix in our plugin, but it will require your database user to have CREATE and ALTER table permissions.

You can read up more on the error here - https://github.com/opencart/opencart/issues/2559

**Comment by shue249** [comment] 2019-12-04 09:34
@Steve-Regal  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.

**Closed by shue249** 2019-12-04 09:34 UTC
