### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#310] opened 2019-12-11 07:36 UTC
Hi,

In last update not impossible to change or add Facebook page:

![image](https://user-images.githubusercontent.com/14319188/70600919-a064f900-1bf9-11ea-8081-22f2d904433f.png)

Also if we saved Pixel account in extension that not saved:

![image](https://user-images.githubusercontent.com/14319188/70601179-2e40e400-1bfa-11ea-9e79-cab4b81faafa.png)
https://gyazo.com/6e0c64415fcf24a9e4635e4b233e068c

**Comment by dtying** [comment] 2019-12-12 07:55
Hi @exitsport, thank you for reporting issue.
1. Currently there's some issue with displaying the pixel / page in the dropdown. We're aware of it.
2. It's not allowed to change page, as this is by design.
3. You can still change the pixel by selecting from the dropdown and click save. And you can verify the update from 'Advanced options'.

**Comment by shue249** [comment] 2020-02-13 05:38
@exitsport  We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Closed by shue249** 2020-02-13 05:38 UTC
