### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by siteadvice** [facebookincubator/Facebook-For-OpenCart#175] opened 2019-05-20 12:05 UTC
I am unable to install the Facebook plugin. I'm using Opencart 2.0.2.0. I have tried it on both my development server and production server with the same result. Permissions seem to be set up correctly as per the screenshot in your installation guide. I've tried using both the regular System > Store > FTP settings and also the iSenseLabs "Quickfix"modification to install the extension. Again, same result: JSON.parse: unexpected character at line 1 column 1 of the JSON data. There is no other diagnostic information - no other warning or error message.

Is this something specific to the Facebook extension or a more general Opencart issue that might be caused by an error in the existing code? Any suggestions on how I might get more disgnostic information that would help you?

FYI I have installed the extension successfully on another website (different Opencart version) so I know it's possible!

**Comment by shue249** [comment] 2019-05-20 23:03
@siteadvice Can you try the steps in the below screenshots so that we can better understand why the installation fails.

![image](https://user-images.githubusercontent.com/11957585/58057161-792fd700-7b96-11e9-90be-41f1a61fb9b8.png)

**Comment by siteadvice** [comment] 2019-05-21 10:58
Unfortunately it does not log anything :-(

![image](https://user-images.githubusercontent.com/1247766/58090678-b3fa3500-7bbf-11e9-9672-5d42ed57dec0.png)

**Comment by shue249** [comment] 2019-05-21 15:53
@siteadvice Have you made any changes to the plugin files? We found that sometimes this error is due to incorrect code syntax in the files.

**Comment by siteadvice** [comment] 2019-05-21 16:33
No - I haven't made any changes. I just downloaded the installation packages and attempted to install them. I have tried it with the latest version from Github as well as the latest version from the Opencart extensions library. Same result with both.

**Comment by shue249** [comment] 2019-05-25 16:06
@siteadvice One more suggestion is to check if on the webserver error log file. You can try to install the plugin again and see if there are any error logs. 

We see this problem happening when there are some code errors in your opencart webserver.

**Comment by shue249** [comment] 2019-05-31 02:07
@siteadvice Are you able to successfully install the plugin now?

**Comment by shue249** [comment] 2019-06-02 20:58
We will be closing out this ticket. Feel free to reach to us if you have any further questions.

**Closed by shue249** 2019-06-02 20:58 UTC

**Comment by siteadvice** [comment] 2019-08-16 17:23
Hi there,
I finally figured out what was causing the installation error!
It was an extension called "Category & Product-Based Fee/Discount". I uninstalled it and the error went away. When I try to upload the Facebook extension now, it says it has been successful. Hurray!
However, there's a slight glitch - there’s no menu button and the module is not shown in Extensions > Modules.
I have given the Administrator group access to the extension in System > Users > User Groups.
And I can manually browse to it via /admin/index.php?route=extension/facebookadsextension&token=XXX and it works, But it’s not very user-friendly. Is there a fix?
Thanks again for trying to help before.
I don't know why Category & Product-Based Fee/Discount caused the conflict, but you might find that bit of information useful in case anyone else has the same problem.
Jon

**Comment by shue249** [comment] 2019-08-19 02:28
@siteadvice Thanks for the feedback, we are glad that we identify the cause of the installation error.

For our plugin, can you look at this video to see if you followed the installation steps? Particularly, you need to refresh the modifications to allow our plugin to appear on your OpenCart admin panel menu bar. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation
