### ISSUE TITLE
After Syncing Products with facebook store problem with checkout link to SEO Url page product

### ISSUE THREAD

**Issue by micorrado** [facebookincubator/Facebook-For-OpenCart#113] opened 2019-02-22 22:00 UTC
Hi, 

I have recently pass all my pages of my opencart store to SEO url , i have delete pixel and setup again config but after have get back all product on my facebook store page there is a problem when you click on checkout URL , link is not good , link send to a bad page and customer is redirect to homepage

Actually i have disable link to my facebook store page and i have re create all my products manually to have products with good link 

Do you known if there is a solution to solve that ?

Thanks

opencart 3.0.2.0

**Comment by shue249** [comment] 2019-02-23 02:31
@micorrado 

Can you share your website URL and your Facebook page for us to understand the issue better.

**Comment by micorrado** [comment] 2019-02-23 06:34
@shue249 

My Webpage : https://www.2ememain.ovh/

My facebook page : https://www.facebook.com/2ememain.ovh

Have a nice day

**Comment by shue249** [comment] 2019-02-26 06:12
@micorrado We have took a look at one example of the product URL link and it shows up fine. As you have disabled the original facebook page shop, we are unable to verify on our side. Can you re-do the Facebook Ads Extension setup again, and then share with us a product on the page shop where the link is wrong (link sends to an empty page and consumer is directed to homepage), so that we can verify this on our side.

We are tracking to use the SEO friendly path in the product in this issue. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/51

Here are some screenshots of the example that we checked. The product URL is https://www.2ememain.ovh/index.php?route=product/product&product_id=63
![image](https://user-images.githubusercontent.com/11957585/53391034-0d433580-39d0-11e9-9914-5d1e39173e4f.png)
![image](https://user-images.githubusercontent.com/11957585/53391087-395eb680-39d0-11e9-884b-886826f9b096.png)
![image](https://user-images.githubusercontent.com/11957585/53391149-6612ce00-39d0-11e9-82bc-b22df15dbb39.png)

**Comment by micorrado** [comment] 2019-02-26 07:10
@shue249 

Helllo 

I have update facebook ads extension with last update and i have re enable pixel link with my facebook store page . 

Could you re check now ?

Thanks

**Comment by micorrado** [comment] 2019-02-26 07:14
@shue249 

After re enabling facebooks links , problem is again present , when you click on links to webpage on an article , a bad page is open and you are only on main web page of the site

**Comment by shue249** [comment] 2019-02-26 07:32
@micorrado Thanks for the quick response. We have found this observation and will like to offer this suggestion to the cause of the problem.

Observation:
1. The URL links on the page shop is shown as below. Notice that the URL link has this %2F
![image](https://user-images.githubusercontent.com/11957585/53394479-61ebae00-39da-11e9-98e0-daceee4de1ce.png)
2. %2F is the URL encoding for the "/" character. https://www.w3schools.com/tags/ref_urlencode.asp
![image](https://user-images.githubusercontent.com/11957585/53394557-a70fe000-39da-11e9-9960-a0999cf74ca3.png)
3. Click on the checkout button and observe what happens on the URL link. It shows %2F at first, then changes to %252F. This is the wrong URL which causes the invalid product page to be shown
![image](https://user-images.githubusercontent.com/11957585/53394705-053cc300-39db-11e9-8d01-70a501f79bf8.png)
4. If you change the URL back to %2F, the product link will be shown correctly

Possible suggestion:
1. A search on Google for this keyword offers some suggestions - https://www.google.com/search?ei=t-d0XNnfC-vi0gLnp6CwAg&q=%252F+redirect+as+%25252F&oq=%252F+redirect+as+%25252F&gs_l=psy-ab.3...742.9675..10367...9.0..0.379.7131.2-19j6......0....2j1..gws-wiz.......0i71j0j0i10j35i39j0i67j38j0i22i30j0i22i10i30j33i160j0i8i13i30j0i8i13i10i30.6PrybRTgbW0
![image](https://user-images.githubusercontent.com/11957585/53394867-77150c80-39db-11e9-92bd-7f9123b55ab5.png)
2. If you are using apache server, you can refer to the first link which offers a possible solution. http://tkurek.blogspot.com/2013/06/252f-instead-of-2f-in-url-apache.html
![image](https://user-images.githubusercontent.com/11957585/53394971-b17ea980-39db-11e9-94cc-901230689781.png)

**Comment by micorrado** [comment] 2019-02-26 07:39
Thanks i will try this solution 

I don't known very much into apache command , i will try to undertsand how i make that

Have a nice day

**Comment by micorrado** [comment] 2019-02-26 07:58
@shue249 

Ok it's done i have add NE on somes intrusction lines on my .htaccess file and now url redirection work

Thanks to you to have look my problem

**Comment by shue249** [comment] 2019-02-26 10:38
Great to hear that. We will be closing off this issue, feel free to reach to us if you have any further questions.

**Closed** 2019-02-26 10:39 UTC
Labels: duplicate, enhancement
