### ISSUE TITLE
Update of token does not work, the access token is still shown as invalid

### ISSUE THREAD

**Issue by joanna-7** [facebookincubator/Facebook-For-OpenCart#144] opened 2019-04-14 06:19 UTC
The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

But there is no button to update token
![2019-04-14 at 08-21-36](https://user-images.githubusercontent.com/22748087/56089100-46f3d100-5e96-11e9-95f7-95a41fe6fcaa.png)

**Comment by joanna-7** [comment] 2019-04-14 06:46
I did what you've mentioned before about "window.facebookAdsToolboxConfig.tokenExpired = 'true'" in the console which shows the button and updates the token, but if I close the tab and reopen a new one the problem will come back, what is the solution?

**Comment by joanna-7** [comment] 2019-04-14 06:47
tho I'm using Plugin Version: 2.0.3

**Comment by shue249** [comment] 2019-04-14 13:31
@joanna-7 Can you share with us a screenshot of how the Facebook Ads Extension module looks like on your OpenCart admin panel.

**Comment by dmitrytrue** [comment] 2019-04-14 16:33
the same problem

**Comment by shue249** [comment] 2019-04-14 23:14
@joanna-7 , @dmitrytrue. We are unable to debug further your problem from our side. Can we ask for you to reach to us directly at ads_extension_opencart@fb.com and we can discuss on the next steps offline.

**Comment by joanna-7** [comment] 2019-04-15 06:17
![2019-04-15 at 08-17-50](https://user-images.githubusercontent.com/22748087/56111011-29d70500-5f5f-11e9-9c4a-e15529bf78ed.png)
@shue249

**Comment by joanna-7** [comment] 2019-04-15 06:18
> @joanna-7 , @dmitrytrue. We are unable to debug further your problem from our side. Can we ask for you to reach to us directly at [ads_extension_opencart@fb.com](mailto:ads_extension_opencart@fb.com) and we can discuss on the next steps offline.

@shue249  Yes sure, how would you like to connect by email?

**Comment by shue249** [comment] 2019-04-15 14:49
@joanna-7 Yes, you can reach us by email.

**Comment by shue249** [comment] 2019-04-15 16:12
@joanna-7 Also, can you update the plugin to the latest version 2.1.5? You are still using the older version - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.5

**Comment by xakou** [comment] 2019-04-16 21:58
Hello, i have the error: Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

**Comment by iq860** [comment] 2019-04-17 08:48
how do i update do i just install the new extension or do i have to remove the old one ?

**Comment by racasanucrinel** [comment] 2019-04-17 10:27
Hello, i installed the latest version 2.1.6 and i have same problem. I can regenerate token but i have this error "The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token."
![Facebook Ads Extension](https://user-images.githubusercontent.com/31210280/56281051-508a6c80-6114-11e9-9276-48f393f3915e.png)

LOGS: 

2019-04-17 10:26:33 - Updating FAE settings - facebook_page_id,facebook_page_token
2019-04-17 10:26:33 - Complete - Updating FAE settings
2019-04-17 10:26:33 - Sync all products using feed
2019-04-17 10:26:33 - Sync all products using feed, remove existing feed file
2019-04-17 10:26:33 - Generating product feed file
2019-04-17 10:26:33 - Generating product feed file header
2019-04-17 10:26:33 - Generating product feed file for batch 0
2019-04-17 10:26:34 - Generating product feed file for batch 1
2019-04-17 10:26:34 - Generating product feed file for batch 2
2019-04-17 10:26:34 - Generating product feed file for batch 3
2019-04-17 10:26:34 - Generating product feed file for batch 4
2019-04-17 10:26:34 - Generating product feed file for batch 5
2019-04-17 10:26:35 - Generating product feed file for batch 6
2019-04-17 10:26:35 - Generating product feed file for batch 7
2019-04-17 10:26:35 - Generating product feed file for batch 8
2019-04-17 10:26:35 - Generating product feed file for batch 9
2019-04-17 10:26:36 - Generating product feed file for batch 10
2019-04-17 10:26:36 - Generating product feed file for batch 11
2019-04-17 10:26:36 - Generating product feed file for batch 12
2019-04-17 10:26:36 - Generating product feed file for batch 13
2019-04-17 10:26:37 - Generating product feed file for batch 14
2019-04-17 10:26:37 - Generating product feed file for batch 15
2019-04-17 10:26:37 - Generating product feed file for batch 16
2019-04-17 10:26:37 - Generating product feed file for batch 17
2019-04-17 10:26:38 - Generating product feed file for batch 18
2019-04-17 10:26:38 - Generating product feed file for batch 19
2019-04-17 10:26:38 - Generating product feed file for batch 20
2019-04-17 10:26:38 - Generating product feed file for batch 21
2019-04-17 10:26:39 - Generating product feed file for batch 22
2019-04-17 10:26:39 - Generating product feed file for batch 23
2019-04-17 10:26:39 - Generating product feed file for batch 24
2019-04-17 10:26:39 - Generating product feed file for batch 25
2019-04-17 10:26:40 - Generating product feed file for batch 26
2019-04-17 10:26:40 - Generating product feed file for batch 27
2019-04-17 10:26:40 - Generating product feed file for batch 28
2019-04-17 10:26:40 - Generating product feed file for batch 29
2019-04-17 10:26:41 - Generating product feed file for batch 30
2019-04-17 10:26:41 - Generating product feed file for batch 31
2019-04-17 10:26:41 - Generating product feed file for batch 32
2019-04-17 10:26:41 - Generating product feed file for batch 33
2019-04-17 10:26:42 - Generating product feed file for batch 34
2019-04-17 10:26:42 - Generating product feed file for batch 35
2019-04-17 10:26:42 - Generating product feed file for batch 36
2019-04-17 10:26:42 - Generating product feed file for batch 37
2019-04-17 10:26:42 - Generating product feed file for batch 38
2019-04-17 10:26:43 - Generating product feed file for batch 39
2019-04-17 10:26:43 - Generating product feed file for batch 40
2019-04-17 10:26:43 - Generating product feed file for batch 41
2019-04-17 10:26:43 - Generating product feed file for batch 42
2019-04-17 10:26:44 - Generating product feed file for batch 43
2019-04-17 10:26:44 - Generating product feed file for batch 44
2019-04-17 10:26:44 - Generating product feed file for batch 45
2019-04-17 10:26:44 - Generating product feed file for batch 46
2019-04-17 10:26:45 - Generating product feed file for batch 47
2019-04-17 10:26:45 - Generating product feed file for batch 48
2019-04-17 10:26:45 - Generating product feed file for batch 49
2019-04-17 10:26:45 - Generating product feed file for batch 50
2019-04-17 10:26:46 - Generating product feed file for batch 51
2019-04-17 10:26:46 - Generating product feed file for batch 52
2019-04-17 10:26:46 - Generating product feed file for batch 53
2019-04-17 10:26:47 - Generating product feed file for batch 54
2019-04-17 10:26:47 - Generating product feed file for batch 55
2019-04-17 10:26:47 - Generating product feed file for batch 56
2019-04-17 10:26:47 - Generating product feed file for batch 57
2019-04-17 10:26:48 - Generating product feed file for batch 58
2019-04-17 10:26:48 - Generating product feed file for batch 59
2019-04-17 10:26:48 - Generating product feed file for batch 60
2019-04-17 10:26:48 - Generating product feed file for batch 61
2019-04-17 10:26:49 - Generating product feed file for batch 62
2019-04-17 10:26:49 - Generating product feed file for batch 63
2019-04-17 10:26:49 - Generating product feed file for batch 64
2019-04-17 10:26:49 - Generating product feed file for batch 65
2019-04-17 10:26:50 - Generating product feed file for batch 66
2019-04-17 10:26:50 - Generating product feed file for batch 67
2019-04-17 10:26:50 - Generating product feed file for batch 68
2019-04-17 10:26:50 - Generating product feed file for batch 69
2019-04-17 10:26:51 - Generating product feed file for batch 70
2019-04-17 10:26:51 - Generating product feed file for batch 71
2019-04-17 10:26:51 - Generating product feed file for batch 72
2019-04-17 10:26:51 - Generating product feed file for batch 73
2019-04-17 10:26:52 - Generating product feed file for batch 74
2019-04-17 10:26:52 - Generating product feed file for batch 75
2019-04-17 10:26:52 - Generating product feed file for batch 76
2019-04-17 10:26:52 - Generating product feed file for batch 77
2019-04-17 10:26:53 - Generating product feed file for batch 78
2019-04-17 10:26:53 - Generating product feed file for batch 79
2019-04-17 10:26:53 - Generating product feed file for batch 80
2019-04-17 10:26:53 - Generating product feed file for batch 81
2019-04-17 10:26:54 - Generating product feed file for batch 82
2019-04-17 10:26:54 - Generating product feed file for batch 83
2019-04-17 10:26:54 - Generating product feed file for batch 84
2019-04-17 10:26:54 - Generating product feed file for batch 85
2019-04-17 10:26:55 - Generating product feed file for batch 86
2019-04-17 10:26:55 - Generating product feed file for batch 87
2019-04-17 10:26:55 - Generating product feed file for batch 88
2019-04-17 10:26:55 - Generating product feed file for batch 89
2019-04-17 10:26:56 - Generating product feed file for batch 90
2019-04-17 10:26:56 - Generating product feed file for batch 91
2019-04-17 10:26:56 - Generating product feed file for batch 92
2019-04-17 10:26:56 - Generating product feed file for batch 93
2019-04-17 10:26:57 - Generating product feed file for batch 94
2019-04-17 10:26:57 - Generating product feed file for batch 95
2019-04-17 10:26:57 - Generating product feed file for batch 96
2019-04-17 10:26:57 - Generating product feed file for batch 97
2019-04-17 10:26:58 - Generating product feed file for batch 98
2019-04-17 10:26:58 - Generating product feed file for batch 99
2019-04-17 10:26:58 - Generating product feed file for batch 100
2019-04-17 10:26:58 - Generating product feed file for batch 101
2019-04-17 10:26:59 - Generating product feed file for batch 102
2019-04-17 10:26:59 - Generating product feed file for batch 103
2019-04-17 10:26:59 - Generating product feed file for batch 104
2019-04-17 10:26:59 - Generating product feed file for batch 105
2019-04-17 10:27:00 - Generating product feed file for batch 106
2019-04-17 10:27:00 - Generating product feed file for batch 107
2019-04-17 10:27:00 - Generating product feed file for batch 108
2019-04-17 10:27:01 - Generating product feed file for batch 109
2019-04-17 10:27:01 - Generating product feed file for batch 110
2019-04-17 10:27:01 - Generating product feed file for batch 111
2019-04-17 10:27:01 - Generating product feed file for batch 112
2019-04-17 10:27:02 - Generating product feed file for batch 113
2019-04-17 10:27:02 - Generating product feed file for batch 114
2019-04-17 10:27:02 - Generating product feed file for batch 115
2019-04-17 10:27:02 - Generating product feed file for batch 116
2019-04-17 10:27:03 - Generating product feed file for batch 117
2019-04-17 10:27:03 - Generating product feed file for batch 118
2019-04-17 10:27:03 - Generating product feed file for batch 119
2019-04-17 10:27:03 - Generating product feed file for batch 120
2019-04-17 10:27:04 - Generating product feed file for batch 121
2019-04-17 10:27:04 - Generating product feed file for batch 122
2019-04-17 10:27:04 - Generating product feed file for batch 123
2019-04-17 10:27:04 - Generating product feed file for batch 124
2019-04-17 10:27:05 - Generating product feed file for batch 125
2019-04-17 10:27:05 - Generating product feed file for batch 126
2019-04-17 10:27:05 - Generating product feed file for batch 127
2019-04-17 10:27:05 - Generating product feed file for batch 128
2019-04-17 10:27:06 - Generating product feed file for batch 129
2019-04-17 10:27:06 - Generating product feed file for batch 130
2019-04-17 10:27:06 - Generating product feed file for batch 131
2019-04-17 10:27:06 - Generating product feed file for batch 132
2019-04-17 10:27:07 - Generating product feed file for batch 133
2019-04-17 10:27:07 - Generating product feed file for batch 134
2019-04-17 10:27:07 - Generating product feed file for batch 135
2019-04-17 10:27:07 - Generating product feed file for batch 136
2019-04-17 10:27:08 - Generating product feed file for batch 137
2019-04-17 10:27:08 - Generating product feed file for batch 138
2019-04-17 10:27:08 - Generating product feed file for batch 139
2019-04-17 10:27:08 - Generating product feed file for batch 140
2019-04-17 10:27:09 - Generating product feed file for batch 141
2019-04-17 10:27:09 - Generating product feed file for batch 142
2019-04-17 10:27:09 - Generating product feed file for batch 143
2019-04-17 10:27:09 - Generating product feed file for batch 144
2019-04-17 10:27:10 - Generating product feed file for batch 145
2019-04-17 10:27:10 - Generating product feed file for batch 146
2019-04-17 10:27:10 - Generating product feed file for batch 147
2019-04-17 10:27:11 - Generating product feed file for batch 148
2019-04-17 10:27:11 - Generating product feed file for batch 149
2019-04-17 10:27:11 - Generating product feed file for batch 150
2019-04-17 10:27:11 - Generating product feed file for batch 151
2019-04-17 10:27:12 - Generating product feed file for batch 152
2019-04-17 10:27:12 - Generating product feed file for batch 153
2019-04-17 10:27:12 - Generating product feed file for batch 154
2019-04-17 10:27:12 - Generating product feed file for batch 155
2019-04-17 10:27:13 - Generating product feed file for batch 156
2019-04-17 10:27:13 - Generating product feed file for batch 157
2019-04-17 10:27:13 - Generating product feed file for batch 158
2019-04-17 10:27:13 - Generating product feed file for batch 159
2019-04-17 10:27:14 - Generating product feed file for batch 160
2019-04-17 10:27:14 - Generating product feed file for batch 161
2019-04-17 10:27:14 - Generating product feed file for batch 162
2019-04-17 10:27:15 - Generating product feed file for batch 163
2019-04-17 10:27:15 - Generating product feed file for batch 164
2019-04-17 10:27:15 - Generating product feed file for batch 165
2019-04-17 10:27:15 - Generating product feed file for batch 166
2019-04-17 10:27:16 - Generating product feed file for batch 167
2019-04-17 10:27:16 - Generating product feed file for batch 168
2019-04-17 10:27:16 - Generating product feed file for batch 169
2019-04-17 10:27:16 - Generating product feed file for batch 170
2019-04-17 10:27:17 - Generating product feed file for batch 171
2019-04-17 10:27:17 - Generating product feed file for batch 172
2019-04-17 10:27:17 - Generating product feed file for batch 173
2019-04-17 10:27:18 - Generating product feed file for batch 174
2019-04-17 10:27:18 - Sync all products using feed, feed file generated
2019-04-17 10:27:18 - Error with syncing all products with feed "FACEBOOK_ACCESS_TOKEN_ERROR"
2019-04-17 10:27:18 - Total number of products = 17383
2019-04-17 10:27:18 - Invalid access token when querying FB page
2019-04-17 10:27:18 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
2019-04-17 10:27:27 - Facebook Ads Extension version = 2.1.6
2019-04-17 10:27:27 - OpenCart version = 3.0.2.0
2019-04-17 10:27:27 - PHP version = 7.2.17
2019-04-17 10:27:27 - Verifying Availability of Facebook Ads Extension Settings Availability
2019-04-17 10:27:27 - FAE Setting ID = true
2019-04-17 10:27:27 - Pixel ID = true
2019-04-17 10:27:27 - Pixel use PII = true
2019-04-17 10:27:27 - Catalog ID = true
2019-04-17 10:27:27 - Page ID = true
2019-04-17 10:27:27 - Page Token = true
2019-04-17 10:27:27 - Feed ID = false
2019-04-17 10:27:27 - Upload ID = false
2019-04-17 10:27:27 - Upload end time = false
2019-04-17 10:27:27 - Messenger plugin = false
2019-04-17 10:27:27 - Messenger plugin, greeting text code customization = false
2019-04-17 10:27:27 - Messenger plugin, locale customization = false
2019-04-17 10:27:27 - Messenger plugin, theme color code customization = false

**Comment by adias** [comment] 2019-04-17 20:33
Hello, same problem after a clean install of OC 3031 and 2.1.6 module.
Tnk's [ ]'s

17-04-2019 20:01:31 - Get Sample product feed
17-04-2019 20:01:31 - Complete - Get Sample product feed
17-04-2019 20:19:28 - Get Sample product feed
17-04-2019 20:19:28 - Complete - Get Sample product feed
17-04-2019 20:21:59 - Get Sample product feed
17-04-2019 20:21:59 - Complete - Get Sample product feed
17-04-2019 20:23:13 - Updating FAE settings - facebook_pixel_id,facebook_pixel_use_pii
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Updating FAE settings - facebook_dia_setting_id
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Updating FAE settings - facebook_catalog_id
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Clear all Facebook products
17-04-2019 20:23:13 - Complete - Clear all Facebook products
17-04-2019 20:23:13 - Updating FAE settings - facebook_page_id,facebook_page_token
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Sync all products using feed
17-04-2019 20:23:13 - Generating product feed file
17-04-2019 20:23:13 - Generating product feed file header
17-04-2019 20:23:13 - Generating product feed file for batch 0
17-04-2019 20:23:14 - Generating product feed file for batch 1
17-04-2019 20:23:14 - Sync all products using feed, feed file generated
17-04-2019 20:23:14 - Error with syncing all products with feed "FACEBOOK_ACCESS_TOKEN_ERROR"
17-04-2019 20:23:14 - Total number of products = 19
17-04-2019 20:23:14 - Syncing using API as fallback
17-04-2019 20:23:14 - Updating FAE settings -
17-04-2019 20:23:14 - Sync all products
17-04-2019 20:23:46 - Deleting FAE settings
17-04-2019 20:23:46 - Complete - Deleting FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_pixel_id,facebook_pixel_use_pii
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_dia_setting_id
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_catalog_id
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_page_id,facebook_page_token
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Sync all products using feed
17-04-2019 20:23:59 - Sync all products using feed, remove existing feed file
17-04-2019 20:23:59 - Generating product feed file
17-04-2019 20:23:59 - Generating product feed file header
17-04-2019 20:23:59 - Generating product feed file for batch 0
17-04-2019 20:23:59 - Generating product feed file for batch 1
17-04-2019 20:23:59 - Sync all products using feed, feed file generated
17-04-2019 20:23:59 - Error with syncing all products with feed "FACEBOOK_ACCESS_TOKEN_ERROR"
17-04-2019 20:23:59 - Total number of products = 19
17-04-2019 20:23:59 - Syncing using API as fallback
17-04-2019 20:23:59 - Updating FAE settings -
17-04-2019 20:23:59 - Sync all products
17-04-2019 20:24:34 - Get Sample product feed
17-04-2019 20:24:34 - Complete - Get Sample product feed
17-04-2019 20:24:36 - Invalid access token when querying FB page
17-04-2019 20:24:36 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:24:39 - Invalid access token when querying FB page
17-04-2019 20:24:39 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:24:47 - Updating FAE settings - facebook_page_id,facebook_page_token
17-04-2019 20:24:47 - Complete - Updating FAE settings
17-04-2019 20:24:48 - Invalid access token when querying FB page
17-04-2019 20:24:48 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:24:51 - Get Sample product feed
17-04-2019 20:24:51 - Complete - Get Sample product feed
17-04-2019 20:24:52 - Invalid access token when querying FB page
17-04-2019 20:24:52 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:26:17 - Get Sample product feed
17-04-2019 20:26:17 - Complete - Get Sample product feed
17-04-2019 20:26:18 - Invalid access token when querying FB page
17-04-2019 20:26:18 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:26:19 - Facebook Ads Extension version = 2.1.6
17-04-2019 20:26:19 - OpenCart version = 3.0.3.1
17-04-2019 20:26:19 - PHP version = 7.2.11
17-04-2019 20:26:19 - Verifying Availability of Facebook Ads Extension Settings Availability
17-04-2019 20:26:19 - FAE Setting ID = true
17-04-2019 20:26:19 - Pixel ID = true
17-04-2019 20:26:19 - Pixel use PII = true
17-04-2019 20:26:19 - Catalog ID = true
17-04-2019 20:26:19 - Page ID = true
17-04-2019 20:26:19 - Page Token = true
17-04-2019 20:26:19 - Feed ID = true
17-04-2019 20:26:19 - Upload ID = true
17-04-2019 20:26:19 - Upload end time = true
17-04-2019 20:26:19 - Messenger plugin = false
17-04-2019 20:26:19 - Messenger plugin, greeting text code customization = false
17-04-2019 20:26:19 - Messenger plugin, locale customization = false
17-04-2019 20:26:19 - Messenger plugin, theme color code customization = false

**Comment by shue249** [comment] 2019-04-17 22:55
> how do i update do i just install the new extension or do i have to remove the old one ?

Yes, you need to remove the old version and install the new version

**Comment by shue249** [comment] 2019-04-17 22:59
@xakou Are you able to see this option to update the token?
![image](https://user-images.githubusercontent.com/11957585/53614459-06f1cb00-3c15-11e9-825b-c042eb15cebb.png)

**Comment by xakou** [comment] 2019-04-18 06:02
@shue249 yes i can see this option. I did Update Token and after sometime i have the error " The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token." 
At the log file i have "Invalid access token when querying FB page" and "Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token."

**Comment by ba4enas** [comment] 2019-04-19 05:56
Hello,
I have trouble installing Facebook Ads Extension. My version of Open Cart in 2.1.0.1. After update the token i have this issue:
 There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.

**Comment by shue249** [comment] 2019-04-19 06:34
Everyone, thank you for your feedback. We are working now to resolve this issue and will inform everyone soonest once we have any update.

**Comment by shue249** [comment] 2019-04-20 07:39
Everyone, we will like to get additional feedback on your opencart plugin setup to help us troubleshoot this issue. If you have access to mysql knowledge, we need your help to send us the access token and page id from your system, for us to verify the reason why the access token remains invalid.
To get these details, you need to do the follow:
 
1. Connect to your MySQL database
2. Run the query – select * from oc_setting where code = 'facebook' (you may need to put in the database accordingly)
3. Find the value for facebook_page_id and facebook_page_token
4. Send us the values for the 2 settings through our email address ads_extension_opencart@fb.com. **DO NOT PASTE THE 2 SETTINGS HERE ON THE TICKET**
 
Again, we apologise for the inconvenience caused.
cidimage001.png@01D4F3DC.C16196E0

**Comment by alexob** [comment] 2019-04-20 09:20
I have the same error and I know how it arises.
I set up plugin, it work correctly. Then in browser I login to Facebook site with my other account. After that if I go to management my ocStore I will get this error.

**Comment by shue249** [comment] 2019-04-20 10:05
@alexob This is really helpful! Can I confirm with you. What happens when you login back to the original account that you used to setup the plugin? Will the error go away?

**Comment by alexob** [comment] 2019-04-20 10:27
> What happens when you login back to the original account that you used to setup the plugin? Will the error go away?

No, the error remains even after login back into the orignal account.

**Comment by ba4enas** [comment] 2019-04-22 13:54
I put the token again but the same problem appeared. Must i put non-expiring Access Token?
Also which token should i get: the catalog or the page?

**Comment by ac5m4ck** [comment] 2019-04-22 21:20
> Everyone, we will like to get additional feedback on your opencart plugin setup to help us troubleshoot this issue. If you have access to mysql knowledge, we need your help to send us the access token and page id from your system, for us to verify the reason why the access token remains invalid.
> To get these details, you need to do the follow:
> 
> 1. Connect to your MySQL database
> 2. Run the query – select * from oc_setting where code = 'facebook' (you may need to put in the database accordingly)
> 3. Find the value for facebook_page_id and facebook_page_token
> 4. Send us the values for the 2 settings through our email address [ads_extension_opencart@fb.com](mailto:ads_extension_opencart@fb.com). **DO NOT PASTE THE 2 SETTINGS HERE ON THE TICKET**
> 
> Again, we apologise for the inconvenience caused.
> ![image](https://user-images.githubusercontent.com/11957585/56454398-816fd900-6382-11e9-8ee1-b1795b5d4395.png)

having the same error here. Email sended.

**Comment by shue249** [comment] 2019-04-23 12:53
For everyone who encounters the problem where the access token continues to show as invalid. Can we understand if you have logged out of Facebook on that same browser which you used to complete the setup?

Thanks to @alexob for flagging this!

**Comment by ac5m4ck** [comment] 2019-04-23 14:01
> For everyone who encounters the problem where the access token continues to show as invalid. Can we understand if you have logged out of Facebook on that same browser which you used to complete the setup?
> 
> Thanks to @alexob for flagging this!

I have facebook account logged in. I can not remember when I last logged out.

**Comment by adias** [comment] 2019-04-23 19:58
hello, im trying to depure the problem, for now i get 2 possible erros...

1 - After update the token (at plugin setting area), i'm check if is valid in the url :
https://developers.facebook.com/tools/debug/accesstoken

And i get this error, a know facebok api error.

![face-log-error-1](https://user-images.githubusercontent.com/1707013/56611189-96997180-65e7-11e9-8850-9ad2809228b8.png)

https://github.com/facebookincubator/facebook-for-woocommerce/issues/943
https://stackoverflow.com/questions/52889519/new-facebook-page-not-visible-to-api

2 - the "=token" is not going wrong? is passing the O.C "user_token" data,  instead facebook token data.
![face-erro-plugin1](https://user-images.githubusercontent.com/1707013/56611661-b3827480-65e8-11e9-860f-4351cbe4cc01.png)

Tnks [ ]'s

**Comment by adias** [comment] 2019-04-23 20:39
Hello, 
i think i resolve the error...

admin/controller/extensions/facebookadsextension.php
line 303: 
: $this->session->data['token'];
to
: 'MY-TOKEN';

line: 307
return 'user_token=' . $this->getToken() . '&token=' . $this->getToken();
to
return 'user_token=' . $this->getToken() . '&token=MY-TOKEN';

The message error disappear and, i dont know but im thinkin its working now, 
im waiting ... the products sync...

![okok](https://user-images.githubusercontent.com/1707013/56614077-7c16c680-65ee-11e9-801b-02eba8a13c36.jpg)

**Comment by Latchezar** [comment] 2019-04-24 07:27
@shue249  I am having the same issue. I'm not sure if the issue is in opencart. I went to the Graph API Explorer and typed in my opencart sql data and i got the following message:
{
  "error": {
    "message": "The 'manage_pages' permission must be granted before impersonating a user's page.",
    "type": "OAuthException",
    "code": 190,
    "fbtrace_id": "**********"
  }
}

So may be I have to give permission somewhere in the Business Manager or may be this can help you resolve the issue if it is in the extension.

**Comment by WilliamYuAnLai** [comment] 2019-04-25 07:56
I still have an error as well

**Comment by shue249** [comment] 2019-04-25 09:42
Thank you to all for the feedback. We are working on addressing the issue. One possible solution for now is not to log out of Facebook on the same browser.

**Comment by shue249** [comment] 2019-04-26 08:35
Thank you to everyone for your patience and thank you for all the information you have send to us. We are working on a fix now and is expecting to land the fix  by end of the week. We will keep everyone posted once the fix is landed.

For now, we have sufficient data points and you do not need to send us anymore invalid access tokens and page ids.

**Comment by dimitris212** [comment] 2019-05-02 16:55
Hello,
I did what you've mentioned before about "window.facebookAdsToolboxConfig.tokenExpired = 'true'" in the console which shows the button and updates the token, but if I close the tab and reopen a new one the problem will come back, what is the solution?

**Comment by xakou** [comment] 2019-05-03 17:59
Hello @shue249 , do you have any news? The problems are true...
#1 "The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token."
#2 The catalog doesn't sync

**Comment by shue249** [comment] 2019-05-05 07:30
Everyone, thank you again for your patience and your information to help us look into this case. We will like to take this chance to share what have we fixed, how should you go about resolving the problem on your OpenCart and what should you do if the access token still shows up as invalid

**What have been done:**
1. Fixed the issue with access token encountering "manage_pages permission is missing"
2. Release version 2.1.7 which shows out the detailed error message with the access token

**What do you need to do:**
1. Update your plugin to version 2.1.7 - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.7

2. If your OpenCart admin panel is showing up an error message showing "invalid access token", do these steps to renew the access token.
![image](https://user-images.githubusercontent.com/11957585/53614459-06f1cb00-3c15-11e9-825b-c042eb15cebb.png)

3. If your OpenCart admin panel is showing up an error message showing "error", do these steps to delete away the existing settings and re-do the settings.
https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

**What happens if the access token is still invalid** 
1. If the error message still shows up as invalid access token due to expired session, check to see if you have logged out of Facebook on the browser. There is a known issue where the access token session becomes invalid if you log out of Facebook. Please comment on this separate ticket and share with us the use case for you logging out of Facebook.

2. If the error message still shows up, pls comment this separate ticket and share with us a screenshot of the error message.
![image](https://user-images.githubusercontent.com/11957585/57190151-f712a200-6f49-11e9-9854-d77f0e18c8b7.png)

**Note to all: We will be closing out this ticket.** 
If you are still encountering error, pls kindly help us to post your screenshot of the error message (pls ensure that you are on version 2.1.7 plugin) on this separate ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/158. This will greatly help us to clearly separate out the new issues so that we can focus on the problems.

**Closed** 2019-05-05 07:30 UTC
Labels: access token remains as invalid after update token

**Comment by shue249** [comment] 2019-05-05 07:32
@joanna-7 , @dmitrytrue, @xakou , @iq860 , @racasanucrinel , @adias, @ba4enas, @alexob , @ac5m4ck, @Latchezar, @WilliamYuAnLai , @dimitris212. Please note the comment above

**Comment by dimitris212** [comment] 2019-05-06 09:13
@shue249
Ok that was fixed!

**Comment by adias** [comment] 2019-05-07 16:19
@shue249 you have a bug here, not fixed at latest version !

You are passing the wrong token, you are passing the opencart token instead of the facebook token.

admin/controller/extensions/facebookadsextension.php
line 303
line: 307

**Comment by adias** [comment] 2019-05-08 21:22
@shue249 I'm so sorry! the module is working now ...
Tnks ! [ ]'

**Comment by shue249** [comment] 2019-05-09 00:39
@adias Glad that it works for you. We have also replied to your comments - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/161

**Comment by dimitris212** [comment] 2019-05-09 07:59
You're right, its working!
I must log out from facebook.

**Comment by Stiliyana1** [comment] 2022-03-15 13:41
Hello, I have the issue, it can't be synced the products and the button UPDATE TOKEN is not shown. Previous was repaired by the code window.facebookAdsToolboxConfig.tokenExpired = 'true', but now is impossible, What should I do? I am using opencart Version 3.0.2.0 and Fb Ads Extension Plugin Version: 2.1.3. I create a new product, but it can't be synced and shown in Fb Catalog. Thx in advance

**Comment by yao-tx** [comment] 2022-03-17 15:54
Hi @Stiliyana1 

The Facebook Ads Extension plugin version 3.1.2 and below have been deprecated and support for those versions have ceased. Do upgrade to the latest version.

**Comment by Stiliyana1** [comment] 2022-03-18 07:12
Thanks for answer,
Yes, I tried to upgrade with the new version of Fb Ads Ext, dowload from fb, but after that I can't sign, due to that the currency wasn't compatible with mine. I uesd Bulgarian Leva 
Greetings
Stiliyana Bakalova









 >-------- Оригинално писмо --------

 >От: TX ***@***.***

 >Относно: Re: [facebookincubator/Facebook-For-OpenCart] Update of token does
 not work, the access token is still shown as invalid (#144)

 >До: facebookincubator/Facebook-For-OpenCart  

 >Изпратено на: 17.03.2022 17:54



 
 
  
  
  
Hi  @Stiliyana1   
  
The Facebook Ads Extension plugin version 3.1.2 and below have been deprecated and support for those versions have ceased. Do upgrade to the latest version.  
   —
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS  or  Android .
