### ISSUE TITLE
Customer group price 

### ISSUE THREAD

**Issue by reorado** [facebookincubator/Facebook-For-OpenCart#16] opened 2018-07-22 04:46 UTC
There are different price for different customer group. The Facebook shop now disclose the non public special price in the OpenCart shop and there is option to change. Pls enable customer group price change asap

**Comment by shue249** [comment] 2018-07-23 00:02
@reorado Thank you for your feedback. Can I understand how do you setup the customer group price on OpenCart, what are the criterias for deciding the various customer groups? Suppose if I am a new customer visiting your website, which is the set of prices I should be seeing?

**Comment by reorado** [comment] 2018-07-23 02:49
@shut, we first set up different user group in the user group setting. For example, basic, VIP, WHOLESALE’s. Any customers who have a login are assigned to a user group and it can be change according to its type.

In the product edit page, there is a tab named “special”, different price can be applied to different user group.

Create prices for different group in that page. If customer do not have a login, only Standard price will been shown, if customer login, price will be shown according to the customer group they were assigned respectively.

Hope you understand the situation, feel free to let me know if you have problems 

從我的 iPhone 傳

**Comment by shue249** [comment] 2018-07-24 12:33
@reorado Thank you for your clear explanation. Can I understand if the Facebook Page Shop is now showing out the standard price from your website. The reason is because on the Facebook Page Shop, we do not have the feature to create customer groups+discounts, hence the prices shown have to be the standard or "default" price that is common for customers who have yet to login.

Right now, our plugin is using the price on the product details page as the price to be shown on Page Shop. 
![image](https://user-images.githubusercontent.com/11957585/43138208-b310fb78-8f80-11e8-8956-e6b5d0a00e88.png)

**Comment by reorado** [comment] 2018-07-24 12:45
Attached is some of the product of my Facebook shop.

It also shows the discount price for the specific customer group. The ski key product are showing 2 prices, default price and discount price.


從我的 iPhone 傳送

**Comment by shue249** [comment] 2018-07-27 00:45
@reorado I am unable to see any attachments. Will you be able to repost them again. 

It will be great if you can give an example of your product on page shop, its corresponding prices on your opencart product module and what is your expectation of how the page shop price should be reflecting.

Like to emphasis here again that Facebook Page shop currently do not have the concept of customer groups, hence it is not able to support showing a specific discount proce for a specific customer group.

**Comment by reorado** [comment] 2018-08-28 07:41
@shue249 ,

Sorry for putting up this case on hold. Please refer to the image attachment. We've set a special price for a VIP group member, which this price should be disclose to this group and this is not a public price.

but in facebook shop, it is showing this price.
![fb-shop-pro-top-2](https://user-images.githubusercontent.com/40544394/44707987-8bce2180-aad8-11e8-9096-9f97eece8de1.png)
![fb-shop-pro-top-1](https://user-images.githubusercontent.com/40544394/44707997-8f61a880-aad8-11e8-828a-de634e743452.png)

**Comment by feliperabreu** [comment] 2018-11-13 14:43
Hi guys, I just want to say that I have the same problem, the wholesale price is being show as the general public price. I manage it the same way as @reorado

**Comment by shue249** [comment] 2019-04-28 02:03
@reorado , @feliperabreu 

Re-visiting this old issue. One way for you to prevent the general public to see the special price is for you to change the code of this file on your webserver (pls ensure that you are using the latest version of the plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.6). By setting the $product_specials to be false, the discount price will not be shown up. However, pls do take note that you will need to edit this code line for subsequent versions of the plugin updates.

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.6/upload/system/library/facebookproductformatter.php#L186

`$product_specials = false;`

**Comment by osworx** [comment] 2019-05-14 17:48
> Re-visiting this old issue. One way for you to prevent the general public to see the special price is for you to change the code of this file on your webserver (pls ensure that you are using the latest version of the plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.6). By setting the $product_specials to be false, the discount price will not be shown up. However, pls do take note that you will need to edit this code line for subsequent versions of the plugin updates.
> 
> https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.6/upload/system/library/facebookproductformatter.php#L186
> 
> `$product_specials = false;`

And why not creating a setting for this module for such?
At every update those edits are lost!
Basically the same like here: https://github.com/facebookincubator/Facebook-For-OpenCart/issues/172

Not every shopowner is a coder and can edit files!

**Comment by shue249** [comment] 2019-05-15 00:04
@osworx Thank you for your feedback! We completely agree with you that we need to make this simple for all shopowners. 

We have considered putting in a setting, however as this toggle requires a entire re-sync of the catalog from OpenCart to Facebook and we are re-visiting on what is the right mechanism to do this re-sync and possibly a re-write of the entire catalog sync mechanism.

One of the factor of consideration is that there are shopowners with a huge catalog, > 50K products, so we need to come up with a right strategy to do his correctly.

**Comment by normdouglas** [comment] 2019-08-02 21:33
> @osworx Thank you for your feedback! We completely agree with you that we need to make this simple for all shopowners.
> 
> We have considered putting in a setting, however as this toggle requires a entire re-sync of the catalog from OpenCart to Facebook and we are re-visiting on what is the right mechanism to do this re-sync and possibly a re-write of the entire catalog sync mechanism.
> 
> One of the factor of consideration is that there are shopowners with a huge catalog, > 50K products, so we need to come up with a right strategy to do his correctly.

I would like to add my support for this feature. Whilst I appreciate the work on this product, it's purpose is so that we can spend money with Facebook... and I think this is a great oversight on the developers point of view which makes the extension virtually useless.
This issue caused a great deal of embarrassment to my business particularly because when you look at the product on the Facebook Catalogue Manager, only the NORMAL price is shown... only when you click on "View more fields" do you see the "Sale Price".
I would strongly encourage you to rectify this issue as fast as possible... so I can start offering our products on Facebook and Instagram.
Thank you.

**Comment by normdouglas** [comment] 2019-08-02 21:59
> > Re-visiting this old issue. One way for you to prevent the general public to see the special price is for you to change the code of this file on your webserver (pls ensure that you are using the latest version of the plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.6). By setting the $product_specials to be false, the discount price will not be shown up. However, pls do take note that you will need to edit this code line for subsequent versions of the plugin updates.
> > https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.6/upload/system/library/facebookproductformatter.php#L186
> > `$product_specials = false;`
> 
> And why not creating a setting for this module for such?
> At every update those edits are lost!
> Basically the same like here: #172
> 
> Not every shopowner is a coder and can edit files!

I can confirm the above fix... however for future readers (and maybe that could be me one day), the precise fix is the following.
Edit the following file > system/library/facebookproductformatter.php
Search for the following on or about line 220
`  private function getDiscountPrice($product) {
    $product_specials = $this->params->getModelCatalogProduct()->
      getProductSpecials($product['product_id']);`
Then replace it with this.
`  private function getDiscountPrice($product) {
    $product_specials = false;`
Hope this helps

**Comment by shue249** [comment] 2019-10-07 22:59
@reorado, @normdouglas  We have released a latest 2.1.11 version of the plugin which provides you an option to choose to sync the special price as discount or to disable the syncing of special price.

If you like to sync for 1 special customer group id price for ALL the products, you can consider making the modifications directly on the plugin files on your webserver. The code pointer will be at - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.11/upload/system/library/facebookproductformatter.php#L227

However, it will not be possible if you are looking to sync the entire customer group structure from OpenCart to Facebook, as Facebook does not have the structure of customer group.

Will be closing out this ticket. Feel free to reach to us if you have further questions.

**Closed by shue249** 2019-10-07 22:59 UTC
Labels: enhancement

**Comment by reorado** [comment] 2019-10-09 16:34
OH great, its here finally. Does it support opencast 3.0.3.2?

**Comment by shue249** [comment] 2019-10-10 00:36
@reorado Yes it supports 3.0.3.2
