### ISSUE TITLE
Missing catalog id from the Facebook Ads Extension settings

### ISSUE THREAD

**Issue by haxcop** [facebookincubator/Facebook-For-OpenCart#160] opened 2019-05-07 11:09 UTC
After updating the version of FB from 2.1.6 to 2.1.7 the tool stopped working and I'm not able to go to the setting or perform any action. 

![image](https://user-images.githubusercontent.com/7826906/57294486-bfc60180-70bf-11e9-8119-f1443cdba1cc.png)

Also, notice the version was already uploaded and updated but keeps showing the previous version. 

![image](https://user-images.githubusercontent.com/7826906/57294563-f3a12700-70bf-11e9-9b84-0713a187c270.png)

When I hit on Manage settings open a new window and goes into a blank page mode.

**Comment by haxcop** [comment] 2019-05-07 11:20
I have cleared the cache, disable the extension, re-enabled - Modification > Refresh 
Tried again, the version now shows the correct, log back into FB Account page. - and receive the same behaviour. 

Log File
2019-05-07 11:06:22 - Complete - Get Sample product feed
2019-05-07 11:06:23 - Failure - no catalog, page or access token, get initial product sync status
2019-05-07 11:06:23 - {"success":true}
2019-05-07 11:06:23 - Error with getting the initial product sync status There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.<br/>Please contact Facebook via our <a href="https://github.com/facebookincubator/Facebook-For-OpenCart/issues" target="_blank">Github</a> if this error keeps showing.
2019-05-07 11:10:28 - Get Sample product feed
2019-05-07 11:10:29 - Complete - Get Sample product feed
2019-05-07 11:10:30 - Failure - no catalog, page or access token, get initial product sync status
2019-05-07 11:10:31 - {"success":true}
2019-05-07 11:10:31 - Error with getting the initial product sync status There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.<br/>Please contact Facebook via our <a href="https://github.com/facebookincubator/Facebook-For-OpenCart/issues" target="_blank">Github</a> if this error keeps showing.
2019-05-07 11:11:49 - Get Sample product feed
2019-05-07 11:11:50 - Complete - Get Sample product feed
2019-05-07 11:11:51 - Failure - no catalog, page or access token, get initial product sync status
2019-05-07 11:11:51 - {"success":true}
2019-05-07 11:11:51 - Error with getting the initial product sync status There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.<br/>Please contact Facebook via our <a href="https://github.com/facebookincubator/Facebook-For-OpenCart/issues" target="_blank">Github</a> if this error keeps showing.
2019-05-07 11:11:55 - Facebook Ads Extension version = 2.1.7
2019-05-07 11:11:55 - OpenCart version = 3.0.3.2
2019-05-07 11:11:55 - PHP version = 7.1.27
2019-05-07 11:11:55 - Verifying Availability of Facebook Ads Extension Settings Availability
2019-05-07 11:11:55 - FAE Setting ID = true
2019-05-07 11:11:55 - Pixel ID = true
2019-05-07 11:11:55 - Pixel use PII = true
2019-05-07 11:11:55 - Catalog ID = false
2019-05-07 11:11:55 - Page ID = true
2019-05-07 11:11:55 - Page Token = true
2019-05-07 11:11:55 - Feed ID = true
2019-05-07 11:11:55 - Upload ID = true
2019-05-07 11:11:55 - Upload end time = true
2019-05-07 11:11:55 - Messenger plugin = true
2019-05-07 11:11:55 - Messenger plugin, greeting text code customization = true
2019-05-07 11:11:55 - Messenger plugin, locale customization = true
2019-05-07 11:11:55 - Messenger plugin, theme color code customization = true

**Comment by shue249** [comment] 2019-05-08 00:01
@haxcop Thank you for the feedback. The details for the log file is really helpful.

We found the cause is due to missing catalog_id. Will you be able to reset the Facebook Ads Extension setting? You will need to delete away the existing settings and re-do the setup again.

You can find the steps to delete away the existing settings here.
https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

**Comment by shue249** [comment] 2019-05-11 04:43
@haxcop Want to check in here if you are able to reset the settings and get the product sync working?

**Comment by squarelabindia** [comment] 2019-05-16 08:53
@shue249 I am also experiencing the same problem. Below is my log data. Resetting the settings is also not helpful.
![Untitled](https://user-images.githubusercontent.com/48884885/57840363-1b8e3a00-77e6-11e9-9226-16a7ad9da919.png)

[RUNWAY FASHION_2019-05-16_08-43-45_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3186151/RUNWAY.FASHION_2019-05-16_08-43-45_facebook_ads_extension.log)

**Comment by haxcop** [comment] 2019-05-16 15:08
I was finally able to solve the issue -
### 1
Clear the browser cache and data
### 2 
Try the steps again

- manage settings
- following the steps here : https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL
- finally, Click on the URL bar of the pop up window browser ( this was important to me as allows me to see the output)

**Comment by shue249** [comment] 2019-05-18 02:40
@haxcop We are glad that this works out for you.

@squarelabindia Can you let us know if the fix works for you.

**Comment by KonstantinGOT** [comment] 2019-05-20 19:20
I want to do the same thing but now when i click manage setting i get this problem.
please help


![Screen Shot 2019-05-20 at 11 58 16](https://user-images.githubusercontent.com/50840258/58046276-ada18580-7af9-11e9-9f5c-f7743da4bd7d.png)

**Comment by shue249** [comment] 2019-05-20 23:06
@KonstantinGOT - Can we better understand what is the browser that you are using? Do you have any ad blocker or popup blocker; is it possible to disable the blockers and see if it works?

**Comment by KonstantinGOT** [comment] 2019-05-20 23:38
@shue249 i was using both chrome and firefox.
when i clear he cache im able to see the login window (email and password) but when entering and loggin in it keep showing this problem

**Comment by KonstantinGOT** [comment] 2019-05-20 23:42
when i firstly download it i was able to see everything (all the settings) there.

**Comment by shue249** [comment] 2019-05-20 23:45
@KonstantinGOT Is it possible for you to record a screen video of what is happening on your setup and share the screen video here with us. Thanks in advance.

**Comment by shue249** [comment] 2019-05-20 23:57
@squarelabindia We looked through your log file. The problem is because the database server was not able to generate the feed file.

![image](https://user-images.githubusercontent.com/11957585/58059081-f3b02500-7b9d-11e9-9f59-556e0f41e1ba.png)

Few questions
1. Have you made any changes to the plugin, especially on the setting on the number of products to extract per batch? Our default setting is to pull out the products in batches of 100 each. From the log, it seems that even pulling out the 1st batch failed
2. How many products do you have on the website
3. Are you able to adjust the memory size of the Mysql database - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

**Comment by KonstantinGOT** [comment] 2019-05-20 23:59
@shue249 you mean to reinstall the plugin again>?

**Comment by KonstantinGOT** [comment] 2019-05-21 00:00
if you like i can add my log

**Comment by KonstantinGOT** [comment] 2019-05-21 00:33
@shue249  can it be issues with facebook? anyone else have this?
or some issues with tokens or id?

**Comment by shue249** [comment] 2019-05-21 00:37
@KonstantinGOT I meant can you record your screen while you perform the steps of setting up Facebook Ads Extension till the point where you encountered the error. We like to visualise the entire flow and try to repo on our side.

**Comment by shue249** [comment] 2019-05-21 00:53
@KonstantinGOT Let us follow up with your problem in your thread - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177

@squarelabindia If you are still having issues on your mysql database, can you create a new ticket and we will follow up on there.

We will be closing out this ticket as the original problem is missing catalog_id.

**Closed by shue249** 2019-05-21 00:53 UTC

**Comment by KonstantinGOT** [comment] 2019-05-21 01:06
@shue249 here you go guys

**Comment by KonstantinGOT** [comment] 2019-05-21 01:07
@shue249 its not supporting mac quick time vid

**Comment by KonstantinGOT** [comment] 2019-05-21 01:10
@shue249 links to the screen video

https://we.tl/t-1JeXmoXFgE
