### ISSUE TITLE
[Object] [Object] error - fb module not getting JSON data 

### ISSUE THREAD

**Issue by zlatina-il** [facebookincubator/Facebook-For-OpenCart#410] opened 2020-06-03 13:49 UTC
There are already many threads related to this error and it has not been fixed yet. When trying to attach the facebook business manager via opencart the following error occurs:
Something went wrong
This may be because of a technical error that we're working to get fixed. Try reloading this page.

![image](https://user-images.githubusercontent.com/17768524/83644168-aa205580-a5b9-11ea-8645-f6a6af9fe7aa.png)
Log file:
2020-06-02 13:53:32 - Pixel ID = false
2020-06-02 13:53:32 - Pixel use PII = false
2020-06-02 13:53:32 - Page ID = false
2020-06-02 13:53:32 - System User Access Token = false
2020-06-02 13:53:32 - Messenger plugin = false

While debugging the admin/view/template/extension/facebookadsextension.tpl file, it was discovered that the JSON data supposed to be returned from opencart.com is not provided at all to the script:
![image](https://user-images.githubusercontent.com/17768524/83644386-e9e73d00-a5b9-11ea-8445-c68c79e42a04.png)

As seen from the screenshot above, the access_token, pixel_id and profiles variables are not retrieved at all by the script, resulting in a false response preventing the application from attaching to the platform. 

![image](https://user-images.githubusercontent.com/17768524/83644531-100cdd00-a5ba-11ea-8888-a939b7853e3b.png)

![image](https://user-images.githubusercontent.com/17768524/83644578-1e5af900-a5ba-11ea-9ccb-85203e76ffa0.png)

Trying to pass the values manually resulted to the following: 
1) Altering the code to pass the values manually:
![image](https://user-images.githubusercontent.com/17768524/83645154-cf619380-a5ba-11ea-9033-ab19f15aa192.png)

2) Installing by passing the values manually results in a "success" state:
![image](https://user-images.githubusercontent.com/17768524/83645280-f750f700-a5ba-11ea-965d-5ee935201a60.png)
![image](https://user-images.githubusercontent.com/17768524/83645407-20718780-a5bb-11ea-908f-38abcb8d4f0b.png)

3) However, after fb business extension has been installed by passing the JSON data values manually, when trying to click the "Manage settings" button fb page returns an error stating "Please set up Facebook Business Extension first before managing settings":

![image](https://user-images.githubusercontent.com/17768524/83645555-4c8d0880-a5bb-11ea-99de-86a8dfc045f7.png)

Log file:
2020-06-03 16:58:37 - Pixel ID = true
2020-06-03 16:58:37 - Pixel use PII = false
2020-06-03 16:58:37 - Page ID = false
2020-06-03 16:58:37 - System User Access Token = false
2020-06-03 16:58:37 - Messenger plugin = false

Please try to find a solution for this as this is a major issue and it's currently impossible to integrate the module with the platform.

**Comment by dtying** [comment] 2020-06-04 04:54
Hi @zlatina-il , thanks for your detailed research!

I'm fully aware of this issue. It should display a generic error message instead of the json code. However, it's not the root cause of their FBE setup failure for anyone who had encountered it.
In your case, kindly share your webstore url so that I can help to check if any backend exception. And this error message should be fixed in the next release.

**Comment by zlatina-il** [comment] 2020-06-04 11:26
This is the website url: https://delmondclothing.com






On Thursday, June 4, 2020, 7:54:25 AM GMT+3, dtying <notifications@github.com> wrote: 







Hi @zlatina-il , thanks for your detailed research!

I'm fully aware of this issue. It should display a generic error message instead of the json code. However, it's not the root cause of their FBE setup failure for anyone who had encountered it.
In your case, kindly share your webstore url so that I can help to check if any backend exception. And this error message should be fixed in the next release.

**Comment by zlatina-il** [comment] 2020-06-04 11:31
https://delmondclothing.com/

**Comment by DrinkZZ** [comment] 2020-06-04 13:32
Hi, i face same issue. opencart 2.2.0.0  store https://DrinkZZ.ro
Any chance for a solution in next days?
Thanks!

**Comment by ivent** [comment] 2020-06-19 18:52
Several errors occurred, but it was not possible to finish whenever this error was not finished, but it was possible to downgrade to version 2.xxx and it is working perfectly now. I hope you can solve these problems in the new versions.

**Comment by dtying** [comment] 2020-07-27 02:08
3.1.0 release fixed [Object object] error.

**Closed by dtying** 2020-07-27 02:08 UTC
Labels: FBE Installation Failure
