### ISSUE TITLE
pixel fb on checkout page

### ISSUE THREAD

**Issue by acjp** [facebookincubator/Facebook-For-OpenCart#369] opened 2020-04-21 20:07 UTC
hi, i make the installation but i can't see the pixel on the checkout page after that i refreshed the page.
can u help me?

**Comment by shue249** [comment] 2020-04-22 02:04
@acjp Want to know if you are using a 3rd party checkout plugin or using the default OpenCart checkout module?

**Comment by acjp** [comment] 2020-04-22 07:33
thanks, default

**Comment by shue249** [comment] 2020-04-22 07:43
@acjp 
1. Can you share your website URL?
2. Are you using any Search Engine Optimization to rename the checkout URL?
3. Can I understand what is the checkout page you are looking at? Is it the page where the customer is confirming the purchase or the Thank you page after customer has confirmed the purchase?

**Comment by acjp** [comment] 2020-04-22 07:48
1.https://www.salumipasini.com/it/checkout/
2.yes
3.where the customer confirm the purchase.

thank you a lot

**Comment by shue249** [comment] 2020-04-24 00:00
@acjp We looked through your website. Only the base pixel code is firing; none of the down funnel pixel events are fired, eg apart from the Thank you page, the product details page is also not firing the ViewContent event.

We believe that this problem is due to the SEO module that you installed which results in our pixel not able to firing the events correctly. Unfortunately, we will not be able to provide support to integrate with this SEO module at this point in time.

You may want to look for alternative plugins to setup the FB pixel on your website.

**Comment by qprod74** [comment] 2020-07-13 08:56
Hi , I have some problem with the add to cart , https://www.qprod.se/ ,  sometimes when the customer press the button "add to cart" it is just showing "loading" and the customer needs to press one more time on the button to add the product to the cart. 
I am using OC Version 3.0.3.2 , and I would like to remove the pixel in " add to cart " , any idea how to do it ? thanks

**Comment by shue249** [comment] 2020-07-24 01:05
@qprod74 are you still facing the problem? Can you help us create a separate ticket?

We will be closing out this ticket. Let us know if you have further questions.

**Closed by shue249** 2020-07-24 01:05 UTC

**Comment by qprod74** [comment] 2020-07-24 08:53
Hi, I have uninstalled FB then it is working. 
I tried to install the latest version that you released some days ago , but facing problem at the dashboard.
