### ISSUE TITLE
Only ViewContent and ViewCategory events are fired on v2.1.5

### ISSUE THREAD

**Issue by Hristow** [facebookincubator/Facebook-For-OpenCart#116] opened 2019-03-08 20:08 UTC
Pixel working only on Product pages with PageView and ViewContent events. All other events don't work.  Can you help me with that problem?
Opencart Version 2.1.0.2
Site: https://nevakids.bg/

**Comment by nichinu** [comment] 2019-03-09 06:19
Same with me... the last purchase event was around 10 days ago. So may be it happened after last update. I am using opencart 3.0.2 and Journal 3 theme.

**Comment by shue249** [comment] 2019-03-10 01:46
@Hristow and @nichinu We will like to see if the problem is due to our recent plugin changes. Will you be able to revert back to the earlier version of 2.1.3 and see if the pixels are able to fire correctly through pixelhelper.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3

**Comment by Hristow** [comment] 2019-03-10 12:33
I changed to old version 2.1.3 and now does not work ViewContent and ViewCategory events. All the others are working. Can you look and fix that?

**Comment by shue249** [comment] 2019-03-11 14:23
@Hristow Are you using an SEO plugin to change the URL for product and category pages?

**Comment by shue249** [comment] 2019-03-11 14:24
Summary on the problem:
On v2.1.3 - all events work except for ViewContent and ViewCategory
On v2.1.5 - Only ViewContent and ViewCategory work, all other events do not work

**Comment by Hristow** [comment] 2019-03-11 15:24
URL on all products and categories are entered manually.

**Comment by Hristow** [comment] 2019-03-13 09:17
Can you look at the code where the problem is? I can give you FTP and Admin access on email?

**Comment by Emwestside** [comment] 2019-03-13 12:48
> @Hristow Are you using an SEO plugin to change the URL for product and category pages?

am having similar problem of pixel not showing up, also i use an SEO extension to change the URL, what do i do to fix this problem. Thanks

**Comment by Hristow** [comment] 2019-03-19 14:54
Will you be able to fix the problem? Two weeks already the pixel does not work correctly...

**Comment by shue249** [comment] 2019-03-21 11:50
@Hristow For now can you revert and use version 2.1.3 while we work on this issue.

**Comment by Hristow** [comment] 2019-03-21 15:55
I am on 2.1.3 version already and ViewCategory and ViewContent are not working ...

**Comment by shue249** [comment] 2019-04-03 00:53
@Hristow  We think we have found the root of the problem. Will you be able to share a file with us so that we can double confirm our hypothesis. The file is /system/engine/front.php on your webserver.

![image](https://user-images.githubusercontent.com/11957585/55445157-bac8dc00-556e-11e9-8828-36e85ecd5890.png)

**Comment by Hristow** [comment] 2019-04-10 13:06
Hello, Here's the file
  



>-------- Оригинално писмо -------- 
>От: shue249 notifications@github.com 
>Относно: Re: [facebookincubator/Facebook-For-OpenCart] Only ViewContent and ViewCategory events are fired on v2.1.5 (#116) 
>До: facebookincubator/Facebook-For-OpenCart   
>Изпратено на: 03.04.2019 03:54 


 
 
  
 @Hristow  We think we have found the root of the problem. Will you be able to share a file with us so that we can double confirm our hypothesis. The file is /system/engine/front.php on your webserver.

**Comment by Hristow** [comment] 2019-04-10 15:41
Did you fix the problem?

**Comment by shue249** [comment] 2019-04-10 17:02
@Hristow Can you attach the file here?

**Comment by Hristow** [comment] 2019-04-10 17:19
[front.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3065014/front.zip)

**Comment by shue249** [comment] 2019-04-16 20:54
@Hristow , we have just released a version 2.1.6 which will we hope to solve the pixel firing issue on your system.

Can you upgrade the plugin to the latest version and see if all the pages are now firing pixel, eg product details page, product category, shopping cart, check out and payment. Pls let us know the status on your website.

**Comment by Hristow** [comment] 2019-04-18 09:50
@shue249 I have updated the extension but now InitiateCheckout, Purchase and Search events are not working... I have been waiting for a month and still, Fb pixel is not working properly. Can you look and fix the problem manually? I can send you FTP and admin access by email.

**Comment by shue249** [comment] 2019-04-20 07:13
@Hristow 
1. Can I understand if the InitiateCheckout, Purchase and Search are working on plugin version 2.1.3?
2. Are there any 3rd party extensions you are using for search and checkout?

**Comment by Hristow** [comment] 2019-04-23 08:35
@shue249 

1. Yes
2. No

**Comment by Hristow** [comment] 2019-05-01 09:15
Hello guys, I am waiting for two months now with useless FB pixel which doesn't work. Is there anyone who can solve my problem please because I am losing data every day?

**Comment by shue249** [comment] 2019-05-02 05:22
@Hristow Apologies for the slow response here, we are evaluating what are the other possible reasons on why this failed on your website. To provide context, our earlier fix worked for some merchants who are having the same problem as you, but unfortunately, it didnt work for you.

Could you send us a copy of this files on your webserver -> <opencart folder>/system/storage/modification/system/engine/front.php

Also are you using journal and/or vqmod?

![image](https://user-images.githubusercontent.com/11957585/57057655-22dd2000-6cdd-11e9-844b-bbcfe18027b4.png)

**Comment by Hristow** [comment] 2019-05-02 09:52
@shue249 Here's a file
I'm using a vqmod.
[front.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3137525/front.zip)

**Comment by shue249** [comment] 2019-05-02 16:22
@Hristow The file you sent out is helpful. We found there is a code block which is not part of OpenCart's default implementation, so this could be a 3rd party extension that you used. We can suggest for you to try the steps in the screenshot out. (We also attached a copy of the update front.php file here for your reference) You can make the changes on your webserver and then try out to see if the pixel firing now works.

If this solution works, then we need to figure out how to make our plugin be even more robust to handle your situation. The solution that you used will not be permanent, as everything you clicked on the refresh modifications button, these changes will be reverted back.

![image](https://user-images.githubusercontent.com/11957585/57090360-35854280-6d39-11e9-9e71-a88800b260be.png)

[front_amended.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3138957/front_amended.zip)

**Comment by Hristow** [comment] 2019-05-07 15:38
@shue249 I changed the file as described above but still: Search, InitiateCheckout and Purchase events do not work..
![Capture](https://user-images.githubusercontent.com/48366152/57312888-47514780-70a3-11e9-8c89-187f3db24327.PNG)

**Comment by Hristow** [comment] 2019-05-07 17:17
@shue249 Sorry my bad. Yes, all events are working after changing the code. 
When I refresh modifications button the file changes back.

**Comment by shue249** [comment] 2019-05-10 10:54
@Hristow You are correct that once you refreshed modifications, the amended file will be changed back. To fix this problem permanently, we need to find the right way to fix this on the plugin codes. For the time being, can you avoid the refresh modifications button or to replace back the amended front.php while we look to see how we can fix this permanently.

**Comment by Hristow** [comment] 2019-05-10 14:40
@shue249 Okay. Please let me know when you fix it.

**Comment by shue249** [comment] 2019-05-31 02:14
@Hristow Thank you for the patience. We have release a version 2.1.9 which helps to resolve your issue. Can you try out the new version and see if it helps to solve the pixel firing issue on your website.

**Comment by shue249** [comment] 2019-06-01 23:38
We will be closing out this task, feel free to reach to us if there are any further questions.

**Closed by shue249** 2019-06-01 23:38 UTC
Labels: bug

**Comment by nichinu** [comment] 2019-06-02 12:55
Hey, The new version solves the problem of the error that was coming on
dashboard. regarding the token update.
But nothing else seems to be effected. Only view "page view" pixel is being
fired and no one else.

I am moving back to the last working version again.2.1.3
