### ISSUE TITLE
Add to Cart button not working (on some custom layouts)

### ISSUE THREAD

**Issue by antisocialbrother** [facebookincubator/Facebook-For-OpenCart#10] opened 2018-06-17 03:19 UTC
With the extension enabled, on some custom designs, the add to cart button it's not working.

Uncaught TypeError: Cannot read property 'target' of undefined
    at Function.add (common_oc.js:224)
    at Object.cart.add (facebook_pixel.js:62)
    at HTMLAnchorElement.onclick (index.php?route=common/home:803)

I'm attaching the common_oc.js file (as txt)
[common_oc.txt](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2108656/common_oc.txt)

**Comment by shue249** [comment] 2018-06-17 06:19
Thanks! We will take a look at this!

**Comment by shue249** [comment] 2018-06-17 07:13
@antisocialbrother Like to share some thoughts. Let me know if this makes sense.

On OpenCart's common.js, the cart.add method is only accepting 2 parameters, productId and quantity. The 3rd parameter, event, on your common_oc.txt is not part of the official Opencart definition. Hence, it will be hard for us to support any custom definition as it will is not a standard deifnition. https://github.com/opencart/opencart/blob/master/upload/catalog/view/javascript/common.js#L156

Are you the developer for the custom designs? Else it will be good to contact the developers for the custom designs.

**Comment by shue249** [comment] 2018-06-19 22:21
@antisocialbrother I will be closing off this ticket as not a bug as the custom designs are adding additional features and not adhering to the default standard of OpenCart.

**Closed by shue249** 2018-06-19 22:21 UTC
