### ISSUE TITLE
Facebook Pixel not working

### ISSUE THREAD

**Issue by Emwestside** [facebookincubator/Facebook-For-OpenCart#120] opened 2019-03-13 09:27 UTC
Kindly assist facebook pixel not firing also the FB chat doesn't show up on the website product catalog already updated.
olmartstores.com

**Comment by shue249** [comment] 2019-03-14 00:33
@Emwestside Can we check if you have setup the Facebook Ads Extension? Also which version of th e plugin are you using?

**Comment by Emwestside** [comment] 2019-03-14 04:19
Sure, what details do you need? Am using the latest version of the
extension.

**Comment by Emwestside** [comment] 2019-03-14 08:28
plugin version 2.1.5

**Comment by Emwestside** [comment] 2019-03-16 17:20
@shue249 Please, find time to say something, we need your help. Thanks

**Comment by shue249** [comment] 2019-03-17 01:36
@Emwestside Apologies for the delay.

1. Which OpenCart version are you using? If you are using version 3.x, can you disable the theme cache.

2. If you are using OpenCart version 2.x, can you try out the earlier v2.1.3 version of the plugin to see if the pixels are able to be fired.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3

**Comment by Emwestside** [comment] 2019-03-17 07:35
Thanks for your help, I have disabled theme cache, still not firing
here is my website name http://olmartstores.com/ , please help look into it.
Thanks again

**Comment by shue249** [comment] 2019-03-18 23:39
@Emwestside 

We found that your case is different from the recent pixel cases that are reported.
We are unable to find the plugin pixel codes inserted into your web store front.
![image](https://user-images.githubusercontent.com/11957585/54570591-11d09c00-4a1a-11e9-932a-0ef9b34b1cf0.png)


2 more things we can suggest:
1. Have you click on the refresh modifications button? https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

2. Have you tried to revert back to the default OpenCart theme and see if the pixel is fired? This is to verify if the cause is due to any 3rd party UI themes that you may be using on your site.

**Comment by Emwestside** [comment] 2019-03-21 12:45
@shue249  Thanks for reaching out , i have tried the precribed solutions, what other hard options do i have to do? Thanks

**Comment by shue249** [comment] 2019-03-21 23:54
@Emwestside The things that we usually see that cause your problem are:
1. Disabling the theme cache
2. Clicking on the Refresh modifications button
3. Incompatible with 3rd party UI themes

You can try to revert back to the original OpenCart UI theme and see if the pixels are fired to determine if it is due to incompatibility with 3rd party UI themes.

You can also check the modifications log for the extensions to determine if the header file is being modified.

**Comment by shue249** [comment] 2019-04-01 03:13
@Emwestside Like to hear from you if the above options work for you?

**Comment by Emwestside** [comment] 2019-04-03 16:08
@shue249 I have tried these options, none seem to work, what else will you have me do?

**Comment by Emwestside** [comment] 2019-04-05 07:28
@shue259 Help!!!!

**Comment by shue249** [comment] 2019-04-08 16:07
@Emwestside I am out of options now. The last thing I could think of is some conflict with a 3rd-party plugin. It will be a tedious job to verify, but you could try out the following.

Setup a fresh installation of OpenCart separately. Install our plugin first, verify if it is working. Then slowly install the other 3rd party plugins one by one and figure out where the failure happens.

**Comment by shue249** [comment] 2019-04-16 20:56
@Emwestside We will be closing off this ticket as a wontfix. Feel free to reach out to us if you have any new findings or progress.

**Closed by shue249** 2019-04-16 20:56 UTC
Labels: wontfix
