### ISSUE TITLE
Big Catalog

### ISSUE THREAD

**Issue by kabetov** [facebookincubator/Facebook-For-OpenCart#303] opened 2019-12-05 03:20 UTC
[Hello!](url)

I have 71K products and no mysql errors at all.
Have the message " There is an error with Facebook Business Extension setup. Click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.
The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 71173 products). Please refer to our FAQ section on "Syncing of OpenCart products to Facebook catalog" for more details."

But nothing helps. =(

**Comment by shue249** [comment] 2019-12-06 14:13
@kabetov 

Can you try to delete away the settings and re-do the setup again - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#delete-the-existing-settings-for-facebook-for-opencart

After which, can you download the log file and share the log file here so that we can help you to debug/troubleshoot.

We have past tickets opened by other OpenCart users who have large/huge catalogs, and most of the time, the problem is due to MySQL server unable to retrieve out all the products for the feed file generation.

**Comment by kabetov** [comment] 2019-12-07 15:25
@shue249 All is good now with a new version!

**Comment by kabetov** [comment] 2019-12-07 16:06
@shue249 at first time it was imported 2800 goods =) nice.
but my Currency in Open Cart is in EURO, in Facebook it is in RUB.

How can I change it? Thanks!

**Comment by shue249** [comment] 2019-12-09 02:32
@kabetov We are glad that the new version works for you.

We have listed out the steps to change the currency on our FAQs (look for point 4), you can look at the screenshots listed on point 4. After you make the currency change, you can do a "Fetch Now" via the Facebook Business Extension popup so that the changes can be sent over to Facebook catalog.

We will be closing out this ticket, feel free to reach to us if you have further questions.

**Closed by shue249** 2019-12-09 02:32 UTC
