### ISSUE TITLE
 The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

### ISSUE THREAD

**Issue by monefff** [facebookincubator/Facebook-For-OpenCart#142] opened 2019-04-13 09:10 UTC
The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

http://prikachi.com/images/538/9544538x.png

I have problem on all of my stores. I don't have button to update. How to update the access token?
Any suggestions?

**Comment by shue249** [comment] 2019-04-13 09:16
@monefff Does this screenshot help you?

![image](https://user-images.githubusercontent.com/11957585/56077526-e621b580-5e0f-11e9-94de-998f4a3812fa.png)

**Comment by monefff** [comment] 2019-04-13 09:23
I am sorry, but I don't have that button on none of my stores. 
http://prikachi.com/images/543/9544543M.png

**Comment by monefff** [comment] 2019-04-13 09:30
To add: My plugin version is 2.1.5

**Comment by shue249** [comment] 2019-04-13 10:03
![image](https://user-images.githubusercontent.com/11957585/56078083-5c291b00-5e16-11e9-94f6-2f4cfae66a4d.png)

**Comment by monefff** [comment] 2019-04-13 10:06
Yes. I will give you 2 pictures on 2 of my stores:

Store 1: http://prikachi.com/images/570/9544570U.png
Store 2: http://prikachi.com/images/571/9544571I.png

**Comment by monefff** [comment] 2019-04-13 10:07
On 5 stores most of them have: Bad Request

**Comment by itshaman** [comment] 2019-04-13 10:35
After near month I have same troble
![image](https://user-images.githubusercontent.com/16690535/56078430-98e21b80-5df0-11e9-8ec2-5b598601df89.png)

I have no The botton "Update Token" 
![image](https://user-images.githubusercontent.com/16690535/56078442-c4650600-5df0-11e9-9f0c-cf76e394c694.png)
NO any changes in my FB acount, same pass, same name
Please Help me update token

**Comment by itshaman** [comment] 2019-04-13 10:37
No "Apdate Token" botton on all my sites ((
Version of module 2.1.5

**Comment by tenableboy** [comment] 2019-04-13 10:45
The same situation. Please give a solution. Thank.

**Comment by Eaglebill** [comment] 2019-04-13 10:48
Mine is doing the same, and no update token button anywhere  to be found. 2.1.5. version
![image](https://user-images.githubusercontent.com/7140192/56078605-b0220880-5df2-11e9-8a60-a51848e25a75.png)

**Comment by serkanbalta** [comment] 2019-04-13 12:24
same here. 
would you please help us how to fix that issue without loosing our catalog and product sets ?
![Screenshot_19](https://user-images.githubusercontent.com/8876539/56079662-3729ad80-5e00-11e9-97c1-a999ffa36abe.jpg)
![Screenshot_20](https://user-images.githubusercontent.com/8876539/56079664-3729ad80-5e00-11e9-94a7-2a3de3e0df77.jpg)

**Comment by dmitrytrue** [comment] 2019-04-13 12:33
No "Apdate Token" botton also
Version of module 2.1.5

**Comment by BarlPro** [comment] 2019-04-13 15:38
Hello. Has the extension stopped working?
My log file
[Интернет-магазин_2019-04-13_17-58-22_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3076398/-._2019-04-13_17-58-22_facebook_ads_extension.log)

**Comment by dmitrytrue** [comment] 2019-04-13 20:25
it didn't start working
products didnt transfer, pixel FB didnt instal...


>Суббота, 13 апреля 2019, 18:38 +03:00 от BarlPro <notifications@github.com>:
>
>Hello. Has the extension stopped working?
>My log file
>Интернет-магазин_2019-04-13_17-58-22_facebook_ads_extension.log
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Mail For Spam

**Comment by shue249** [comment] 2019-04-14 01:06
@monefff , @itshaman , @tenableboy , @Eaglebill , @dmitrytrue , @BarlPro , @serkanbalta 

We are working on a fix now. In the meantime, you can do this to be able to see the "Update Token" option.

1. Access the Facebook Ads Extension module on your OpenCart admin panel using Chrome browser
2. Launch the Javascript console
![image](https://user-images.githubusercontent.com/11957585/53614531-41f3fe80-3c15-11e9-95d1-d5e300ce5ed7.png)
3. Copy, paste and run this code on the javascript console
`window.facebookAdsToolboxConfig.tokenExpired = 'true'`
4. Launch the Facebook Ads Extension popup and you should be able to see the option to update the token.
![image](https://user-images.githubusercontent.com/11957585/53614459-06f1cb00-3c15-11e9-825b-c042eb15cebb.png)

**Comment by itshaman** [comment] 2019-04-14 11:05
Its work for me, thanks

**Comment by monefff** [comment] 2019-04-14 12:11
@shue249, it solves the problem, but only for a while. I tried it on 5 stores, 3 of them are working, the other 2 are bad request again, and I have to sync them again and again...

**Comment by shue249** [comment] 2019-04-14 13:30
@monefff Can you explain in more details for the other 2 stores that shows Bad request. Does it mean that you complete the steps above, clicked on the Update Token button. After which you refresh the page and it shows as Bad request again?

**Comment by BarlPro** [comment] 2019-04-14 14:13
> он не начал работать, продукты не передавались, пиксель FB не устанавливался ...
> [...](#)
> Суббота, 13 апреля 2019, 18:38 +03: 00 от BarlPro ***@***.***>: Здравствуйте. Перестало работать расширение? Мой файл журнала Интернет-магазин_2019-04-13_17-58-22_facebook_ads_extension.log - Вы получаете это, потому что прокомментировали. Ответьте на это письмо напрямую, просмотрите его на GitHub или отключите тему.
> - Почта для Спама

I have a pixel installed, there are no errors when checking on facebook. Errors only when adding new products in the module.

**Comment by BarlPro** [comment] 2019-04-14 14:18
![333333333333](https://user-images.githubusercontent.com/49591628/56094135-46305e80-5ed9-11e9-9aff-8d9cd6169874.jpg)

**Comment by shue249** [comment] 2019-04-14 14:21
@BarlPro We are working on a fix now, the problem is due to invalid access token. I believe you are not able to see the option to Update token. In the meantime, you can do this to be able to see the "Update Token" option.

1. Access the Facebook Ads Extension module on your OpenCart admin panel using Chrome browser
2. Launch the Javascript console
![image](https://user-images.githubusercontent.com/11957585/53614531-41f3fe80-3c15-11e9-95d1-d5e300ce5ed7.png)
3. Copy, paste and run this code on the javascript console
`window.facebookAdsToolboxConfig.tokenExpired = 'true'`
4. Launch the Facebook Ads Extension popup and you should be able to see the option to update the token.
![image](https://user-images.githubusercontent.com/11957585/53614459-06f1cb00-3c15-11e9-825b-c042eb15cebb.png)

**Comment by BarlPro** [comment] 2019-04-14 14:31
i don't have that line that's what i have
![4444](https://user-images.githubusercontent.com/49591628/56094258-11250b80-5edb-11e9-94d8-1cd5159dd78b.jpg)

**Comment by BarlPro** [comment] 2019-04-14 14:41
it turned out to update, the error warning is gone

**Comment by shue249** [comment] 2019-04-14 14:41
@BarlPro You have to manually copy-paste in that line into the console log. For your information, this is running a line of code on your chrome browser and this code line below will allow the "Update token" to be shown.

`window.facebookAdsToolboxConfig.tokenExpired = 'true'`

**Comment by dmitrytrue** [comment] 2019-04-14 14:48
i`ve updated token by this way
![22](https://user-images.githubusercontent.com/49588392/56094455-4cc0d500-5edd-11e9-9bed-0b6dca8acc69.JPG)

but after refresh OpenCart admin panel, the same
![23](https://user-images.githubusercontent.com/49588392/56094467-6eba5780-5edd-11e9-82e6-775f5e15b447.JPG)

**Comment by BarlPro** [comment] 2019-04-14 15:02
I have no error, clicked to update and new products appeared on Facebook

**Comment by shue249** [comment] 2019-04-14 23:12
@BarlPro Can we understand that the problem has been solved on your OpenCart? ie, you are able to refresh the token successfully.

**Comment by shue249** [comment] 2019-04-14 23:15
@monefff We are unable to debug further your problem for the other 2 stores from our side. Can we ask for you to reach to us directly at ads_extension_opencart@fb.com and we can discuss on the next steps offline.

**Comment by BarlPro** [comment] 2019-04-15 07:15
I updated on your recommendation, my error disappeared. Thanks for the help.

**Comment by serkanbalta** [comment] 2019-04-15 08:51
@shue249 thanks, it worked.

**Comment by Mayaldossari** [comment] 2019-04-15 12:33
> @BarlPro Can we understand that the problem has been solved on your OpenCart? ie, you are able to refresh the token successfully.

Hi..
I have this issue exactly :(((
how to solve it ??

**Comment by Mayaldossari** [comment] 2019-04-15 12:38
@shue249 " You have to manually copy-paste in that line into the console log. For your information, this is running a line of code on your chrome browser and this code line below will allow the "Update token" to be shown."
> 
> `window.facebookAdsToolboxConfig.tokenExpired = 'true'`
//////////////////////////////////////////////////
I did all steps but if refresh  page the error appear ??

**Comment by shue249** [comment] 2019-04-15 14:48
@Mayaldossari  We are unable to debug further your problem from our side. Can we ask for you to reach to us directly at ads_extension_opencart@fb.com and we can discuss on the next steps offline.

**Comment by shue249** [comment] 2019-04-16 20:46
Everyone, we have just released a version 2.1.6 which will solve the "error" or "Bad request" error message, allowing you to update the token and without the need to run any codes on the console. Please update to the latest version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.6

However, if you still encounter the "Invalid access token" even after updating the token, pls comment in this ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144 and we will follow up there.

Closing off this ticket for now.

**Closed by shue249** 2019-04-16 20:46 UTC
Labels: access token invalid

**Comment by adias** [comment] 2019-04-17 20:32
Hello, same problem after a clean install of o.c 3031 and 2.1.6. 
Tnk's [ ]'s

17-04-2019 20:01:31 - Get Sample product feed
17-04-2019 20:01:31 - Complete - Get Sample product feed
17-04-2019 20:19:28 - Get Sample product feed
17-04-2019 20:19:28 - Complete - Get Sample product feed
17-04-2019 20:21:59 - Get Sample product feed
17-04-2019 20:21:59 - Complete - Get Sample product feed
17-04-2019 20:23:13 - Updating FAE settings - facebook_pixel_id,facebook_pixel_use_pii
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Updating FAE settings - facebook_dia_setting_id
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Updating FAE settings - facebook_catalog_id
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Clear all Facebook products
17-04-2019 20:23:13 - Complete - Clear all Facebook products
17-04-2019 20:23:13 - Updating FAE settings - facebook_page_id,facebook_page_token
17-04-2019 20:23:13 - Complete - Updating FAE settings
17-04-2019 20:23:13 - Sync all products using feed
17-04-2019 20:23:13 - Generating product feed file
17-04-2019 20:23:13 - Generating product feed file header
17-04-2019 20:23:13 - Generating product feed file for batch 0
17-04-2019 20:23:14 - Generating product feed file for batch 1
17-04-2019 20:23:14 - Sync all products using feed, feed file generated
17-04-2019 20:23:14 - Error with syncing all products with feed "FACEBOOK_ACCESS_TOKEN_ERROR"
17-04-2019 20:23:14 - Total number of products = 19
17-04-2019 20:23:14 - Syncing using API as fallback
17-04-2019 20:23:14 - Updating FAE settings - 
17-04-2019 20:23:14 - Sync all products
17-04-2019 20:23:46 - Deleting FAE settings
17-04-2019 20:23:46 - Complete - Deleting FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_pixel_id,facebook_pixel_use_pii
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_dia_setting_id
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_catalog_id
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Updating FAE settings - facebook_page_id,facebook_page_token
17-04-2019 20:23:59 - Complete - Updating FAE settings
17-04-2019 20:23:59 - Sync all products using feed
17-04-2019 20:23:59 - Sync all products using feed, remove existing feed file
17-04-2019 20:23:59 - Generating product feed file
17-04-2019 20:23:59 - Generating product feed file header
17-04-2019 20:23:59 - Generating product feed file for batch 0
17-04-2019 20:23:59 - Generating product feed file for batch 1
17-04-2019 20:23:59 - Sync all products using feed, feed file generated
17-04-2019 20:23:59 - Error with syncing all products with feed "FACEBOOK_ACCESS_TOKEN_ERROR"
17-04-2019 20:23:59 - Total number of products = 19
17-04-2019 20:23:59 - Syncing using API as fallback
17-04-2019 20:23:59 - Updating FAE settings - 
17-04-2019 20:23:59 - Sync all products
17-04-2019 20:24:34 - Get Sample product feed
17-04-2019 20:24:34 - Complete - Get Sample product feed
17-04-2019 20:24:36 - Invalid access token when querying FB page
17-04-2019 20:24:36 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:24:39 - Invalid access token when querying FB page
17-04-2019 20:24:39 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:24:47 - Updating FAE settings - facebook_page_id,facebook_page_token
17-04-2019 20:24:47 - Complete - Updating FAE settings
17-04-2019 20:24:48 - Invalid access token when querying FB page
17-04-2019 20:24:48 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:24:51 - Get Sample product feed
17-04-2019 20:24:51 - Complete - Get Sample product feed
17-04-2019 20:24:52 - Invalid access token when querying FB page
17-04-2019 20:24:52 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:26:17 - Get Sample product feed
17-04-2019 20:26:17 - Complete - Get Sample product feed
17-04-2019 20:26:18 - Invalid access token when querying FB page
17-04-2019 20:26:18 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
17-04-2019 20:26:19 - Facebook Ads Extension version = 2.1.6
17-04-2019 20:26:19 - OpenCart version = 3.0.3.1
17-04-2019 20:26:19 - PHP version = 7.2.11
17-04-2019 20:26:19 - Verifying Availability of Facebook Ads Extension Settings Availability
17-04-2019 20:26:19 - FAE Setting ID = true
17-04-2019 20:26:19 - Pixel ID = true
17-04-2019 20:26:19 - Pixel use PII = true
17-04-2019 20:26:19 - Catalog ID = true
17-04-2019 20:26:19 - Page ID = true
17-04-2019 20:26:19 - Page Token = true
17-04-2019 20:26:19 - Feed ID = true
17-04-2019 20:26:19 - Upload ID = true
17-04-2019 20:26:19 - Upload end time = true
17-04-2019 20:26:19 - Messenger plugin = false
17-04-2019 20:26:19 - Messenger plugin, greeting text code customization = false
17-04-2019 20:26:19 - Messenger plugin, locale customization = false
17-04-2019 20:26:19 - Messenger plugin, theme color code customization = false

**Comment by shue249** [comment] 2019-04-17 22:53
@adias Are you able to see the option to update the token?
![image](https://user-images.githubusercontent.com/11957585/53614459-06f1cb00-3c15-11e9-825b-c042eb15cebb.png)

**Comment by FBA-Gal** [comment] 2019-05-20 15:24
I have tried adding the "window.facebookAdsToolboxConfig.tokenExpired = 'true'" line but get the following 
VM5071:1 Uncaught TypeError: Cannot set property 'tokenExpired' of undefined
    at <anonymous>:1:46

**Comment by FBA-Gal** [comment] 2019-05-20 15:28
I meant to add .... I see the mention of the updated version above, but when I clicked on it, I note that it's "for OpenCart versions 2.2.0.0 to 2.3.0.2".  Is there a transposition in that first version number?  (I'm using OpenCart version 2.0.2.0, not 2.2.0.0)

**Comment by shue249** [comment] 2019-05-20 23:40
@FBA-Gal Our plugin supports from 2.0.1.1 to 2.3.0.2

1. Which browser are you using
2. What is the plugin version you are using?
3. Can have clear cache and force restart of the browser?
4. Can you open up the console window and show if there's any error messages

**Comment by FBA-Gal** [comment] 2019-05-21 00:30
@shue249 I typically work on Chrome, and have for quite some time, even before I installed the plugin. I'm currently using Plugin Version 2.0.3 and see that you have an updated version, but wasn't sure if it would work for me since it says it's "for OpenCart versions 2.2.0.0 to 2.3.0.2" yet I have 2.0.2.0. Now that you've indirectly confirmed that the reference to 2.2.0.0 was incorrect, I'll try installing the updated version and see if that fixes the issue.  (Up until a few weeks ago, the plugin had been working without incident.)

**Comment by sbillis** [comment] 2019-11-23 08:36
This solution:
Copy, paste and run this code on the javascript console
window.facebookAdsToolboxConfig.tokenExpired = 'true'

works on Opencart 3.0.3.2 with 2.1..13 extension version !
