### ISSUE TITLE
Facebook Catalog Sync Problem

### ISSUE THREAD

**Issue by creativegg** [facebookincubator/Facebook-For-OpenCart#308] opened 2019-12-10 09:01 UTC
Hi, we have a problem connecting catalog to Facebook.
A warring appeares in the Facebook Business Extension: Warning: We have updated the catalog sync process and requires you to do an update immediately. Please click on Facebook Business Extension, Manage Settings, go to Advanced Options and follow the instructions. View steps

But the Catalog does not sync, and this message appears: Catalog Sync Failed
Your catalog failed to sync. Please try to sync your products from OpenCart again.

I am attaching screenshots.
How can
![Facebook_BE_Problem_1](https://user-images.githubusercontent.com/58726080/70514447-579b3a80-1b3c-11ea-9f98-e8789c1d125e.jpg)
![Facebook_BE_Problem_2](https://user-images.githubusercontent.com/58726080/70514448-579b3a80-1b3c-11ea-8357-9518136fa169.jpg)

 we fix it?

**Comment by shue249** [comment] 2019-12-10 09:04
@creativegg Like to confirm that your webstore URL is https://creativegg.com/

**Comment by creativegg** [comment] 2019-12-10 09:05
Yes.

Regards,
Toni



FrontRoom Ltd.
Sofia 1421, Bulgaria
39-41 Tsvetna Gradina Str.
T: +359 2 488 19 49
M: +359 889 31 85 61
www.frontroom.eu

**Comment by dtying** [comment] 2019-12-10 09:30
@creativegg 
Thank you for the error reporting.

In order for us to better identify the issue, can you follow the instructions and send us the screenshot?
1. Open the extension and navigate to 'Advanced Options'
2. Right click on the page, click'Inspect' to open Chrome Inspector. Then open 'Network' tab.
3. Type 'setup' in the filter, check its 'Response' and send us the details 
![Screen Shot 2019-12-10 at 10 12 13 AM](https://user-images.githubusercontent.com/21333308/70516835-a06de600-1b72-11ea-8ddf-98675db1efe9.png)

**Comment by creativegg** [comment] 2019-12-10 09:37
![ScreenShot3](https://user-images.githubusercontent.com/58726080/70517584-6e905b80-1b41-11ea-858e-be94a818a332.jpg)

**Comment by dtying** [comment] 2019-12-10 09:40
@creativegg could you click on on it, and open Reponse tab? I want to view the details of it.

**Comment by creativegg** [comment] 2019-12-10 09:43
Here it is :)
![ScreenShot4](https://user-images.githubusercontent.com/58726080/70517990-35a4b680-1b42-11ea-9d3e-378e65060c56.jpg)

**Comment by creativegg** [comment] 2019-12-10 10:37
Did you find the problem?

**Comment by dtying** [comment] 2019-12-10 11:42
@creativegg yes we’re looking into the issue currently. It may take sometime to fix the issue, and we’ll keep you updated.

**Comment by creativegg** [comment] 2019-12-10 11:45
Thank you! We really need to fix it ASAP as it is our busiest time of the year.

**Comment by dtying** [comment] 2019-12-10 11:51
@creativegg if it’s really urgent, you can re-install the older version release first, and use it in the same way as before. Once we fix the issue, then you upgrade it again.

**Comment by creativegg** [comment] 2019-12-10 12:15
The old version doesn't work as well.

**Comment by itshaman** [comment] 2019-12-11 16:32
Have the same troble
![изображение](https://user-images.githubusercontent.com/16690535/70640305-ce275d80-1c4c-11ea-950b-7258b15997a0.png)

Response is html page

`<!DOCTYPE html><html lang="en" id="facebook"><head><title>Error</title><meta charset="utf-8" /><meta http-equiv="Cache-Control" content="no-cache" /><meta name="robots" content="noindex,nofollow" /><style>html, body { color: #333; font-family: 'Lucida Grande', 'Tahoma', 'Verdana', 'Arial', sans-serif; margin: 0; padding: 0; text-align: center;}
#header { height: 30px; padding-bottom: 10px; padding-top: 10px; text-align: center;}
#icon { width: 30px;}
.core { margin: auto; padding: 1em 0; text-align: left; width: 904px;}
h1 { font-size: 18px;}
p { font-size: 13px;}
.footer { border-top: 1px solid #ddd; color: #777; float: left; font-size: 11px; padding: 5px 8px 6px 0; width: 904px;}</style></head><body><div id="header"><a href="//www.facebook.com/"><img id="icon" src="//static.facebook.com/images/logos/facebook_2x.png" /></a></div><div class="core"><h1>Sorry, something went wrong.</h1><p>We&#039;re working on getting this fixed as soon as we can.</p><p><a id="back" href="//www.facebook.com/">Go Back</a></p><div class="footer"> Facebook &#169; 2019 &#183; <a href="//www.facebook.com/help/">Help</a></div></div><script>
              document.getElementById("back").onclick = function() {
                if (history.length > 1) {
                  history.back();
                  return false;
                }
              };
            </script></body></html>`

How can I fix it?

**Comment by dtying** [comment] 2019-12-12 04:57
@creativegg 
I checked that your issue was caused by data discrepancy and validation exception in Facebook. Can you try remove the existing setting, and re-create a new one?
1. Install the latest release [here](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1).
2. Open Extension. Go to 'Ad Setup' -> 'Advanced Settings' -> 'Remove', wait for it to complete. Note that your current OpenCart catalog on Facebook will be deleted.
3. Go through the setup to create a new setting.
4. After setup finished, follow the highlighted link in screenshot to view your products uploaded to Facebook. You can verify the details of your feed daily schedule by clicking 'Product Data Sources' in the left navigation menu.
![Screen Shot 2019-12-12 at 12 49 35 PM](https://user-images.githubusercontent.com/21333308/70683790-b00a3d80-1cde-11ea-83c1-5c5bccc697ff.png)

**Comment by dtying** [comment] 2019-12-12 04:59
Hi @itshaman, can you provide your webstore url for me?

**Comment by Eaglebill** [comment] 2019-12-12 16:09
I am having the same problem. 
With the new update the sync is having trouble.
![save failed](https://user-images.githubusercontent.com/7140192/70727753-d7760000-1d08-11ea-886c-bcc436f3934f.jpg)
![network](https://user-images.githubusercontent.com/7140192/70728645-794a1c80-1d0a-11ea-8709-ac2cd9a1df91.jpg)

**Comment by dtying** [comment] 2019-12-13 07:14
Hi @Eaglebill , your issue was due to the same problem with @creativegg 
Can you follow the instructions in this [comment](https://github.com/facebookincubator/Facebook-For-OpenCart/issues/308#issuecomment-564849885)  and let me know if it can work?

**Comment by Eaglebill** [comment] 2019-12-13 17:14
Hello again @dtying , your solution seems to have solved partially the issue.
The products synced successfully to the Facebook store, but i can't seem to be able to tag them in my posts. I am not sure if this is another problem, but i think it's associated with  Facebook ads extensions since I was able to tag them properly before. I have already submitted a ticket for the particular issue with Facebook developers as well.

**Comment by itshaman** [comment] 2019-12-14 23:28
> 
> 
> Hi @itshaman, can you provide your webstore url for me?

site https://vikart-molbert.ru

Reinstall is very hard
more than 5000 items, pixel with statistc data...

Can I fix settings any different way?
Change it in MYSQL ? or in module files?

**Comment by creativegg** [comment] 2019-12-15 07:13
Hi, we removed the catalog and installed it again and it seems to work
fine. Thank you!

Do you know how we can change the schedule, so it update every 6 hours?

**Comment by dtying** [comment] 2019-12-16 02:16
Hi @itshaman , as the Catalog Migration failure is caused by data issue, there's no simple way to fix it from code base change only. 
After reinstall, the catalog feed only extracts active products from your site and sync on a daily basis.

**Comment by dtying** [comment] 2019-12-16 02:18
Hi @creativegg, FBE currently doesn't support customize the schedule. It defaults on daily schedule.

**Comment by itshaman** [comment] 2020-01-02 22:15
After remove settings and install it againg 
i have some trouble in my catalog
Link to my product, image and check outpage generate at HTTP protocol
at site installed & configured https all other extensions use it
How fix it?

**Comment by shue249** [comment] 2020-01-06 00:16
@itshaman Can you help us to better understand your problem.

1. What is your catalog? Will you be able to share with us the catalog id or the link or your website URL

2. What is the problem you are seeing with the new catalog? Can you share with us an example of the problem through a specific product?

**Comment by beachgeek** [comment] 2020-02-07 05:18
shue249. having the same issues. catalog cannot sync for errors which it does not specify. 
Plus I noticed that at the top is says Facebook extension for Magento NOT Opencart? I downloaded and installed the opencart here? 

![image](https://user-images.githubusercontent.com/44654428/74003081-fa064d00-4936-11ea-8342-e1d904d4ea7a.png)

**Comment by beachgeek** [comment] 2020-02-07 05:21
when you click on Help Center on the top right it takes you to this page for a Magento install. 


![image](https://user-images.githubusercontent.com/44654428/74003180-579a9980-4937-11ea-8b81-f5c068f8feb3.png)

**Comment by shue249** [comment] 2020-03-11 02:41
@beachgeek Apologies for missing out this issue. Want to check if you are still facing sync issues?

**Comment by shue249** [comment] 2020-03-15 07:17
Closing this ticket. Feel free to reach to us if you have further questions.

**Closed by shue249** 2020-03-15 07:17 UTC
