### ISSUE TITLE
Large number of products

### ISSUE THREAD

**Issue by Bolshaksa** [facebookincubator/Facebook-For-OpenCart#285] opened 2019-11-01 18:19 UTC
Hello!

After installing the module, i see such a message

"There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.
The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 522351 products)."

Can you answer me please, how i can fix it?

**Comment by shue249** [comment] 2019-11-06 02:36
@Bolshaksa 

We believe the problem is because of the large number of products that need to be sync over to Facebook. We have documented some suggestions on our FAQ for your reference - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

**Comment by shue249** [comment] 2019-12-04 09:33
@Bolshaksa  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.

**Closed by shue249** 2019-12-04 09:33 UTC
