### ISSUE TITLE
Facebook Ads Extension error - "Sorry, something went wrong"

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#177] opened 2019-05-20 16:22 UTC
Hello 
I try to set up the Facebook ad extension to have my catalogs there but face couple problems.
it says to go to manage setting to delete it but when i go there it says there is another problem 

![Screen Shot 2019-05-20 at 9 19 32](https://user-images.githubusercontent.com/50840258/58036713-a3bf5880-7ae0-11e9-8f03-cb69550d760c.png)
![Screen Shot 2019-05-20 at 9 19 44](https://user-images.githubusercontent.com/50840258/58036733-af128400-7ae0-11e9-9049-3d61b15c8bf2.png)

**Comment by 1991x** [comment] 2019-05-21 00:39
Hi, I have same problem. Get error message when click manage setting button

**Comment by shue249** [comment] 2019-05-21 00:44
@1991x Thank you for your feedback. Will you be able to record a screen recording of the steps that leads to the error and share with us. Thanks in advance.

**Comment by 1991x** [comment] 2019-05-21 01:23
This is the record https://drive.google.com/file/d/1Nb5Fek6uLzC-1KZRdPj10bvGyB4QUcPc/view

**Comment by KonstantinGOT** [comment] 2019-05-21 01:28
@1991x thank you for your help on video

**Comment by KonstantinGOT** [comment] 2019-05-21 01:29
https://we.tl/t-1JeXmoXFgE
here is mine with more details

**Comment by 1991x** [comment] 2019-05-21 01:31
I've tried to empty cache and hard reload, use different browser, reinstall but it doesn't work

**Comment by KonstantinGOT** [comment] 2019-05-21 01:49
@1991x same here

**Comment by shue249** [comment] 2019-05-21 02:40
@1991x , @KonstantinGOT Thanks for your help. This is helpful for us. We will continue to deep dive to figure out the root cause.

**Comment by svremeto** [comment] 2019-05-21 10:34
Same with me - https://drive.google.com/file/d/1Nb5Fek6uLzC-1KZRdPj10bvGyB4QUcPc/view

**Comment by shue249** [comment] 2019-05-21 13:32
@1991x , @KonstantinGOT Can we ask for you to reach to us via email at ads_extension_opencart@fb.com. There is something we like to discuss with you offline. Pls also indicate your github user name so that it is easier for us to make the connection.

**Comment by KonstantinGOT** [comment] 2019-05-21 15:39
@shue249  sent

**Comment by 1991x** [comment] 2019-05-21 23:43
@shue249 sent

**Comment by shue249** [comment] 2019-05-22 00:07
@1991x , @KonstantinGOT Thank you for your speedy response. We have landed a fix for your issue. Can you try to launch Facebook Ads Extension again and see if it is now working properly.

**Comment by medeirosrafael** [comment] 2019-05-22 00:08
@shue249 i'm facing same issue here.. i sent a email for you

**Comment by KonstantinGOT** [comment] 2019-05-22 00:12
@shue249  what steps should we do?

**Comment by KonstantinGOT** [comment] 2019-05-22 00:17
@shue249 i did the reinstall and cache delete but still same things

**Comment by Eaglebill** [comment] 2019-05-22 06:07
I have the same problem, when i click manage settings the pop-up window says error.
![image](https://user-images.githubusercontent.com/7140192/58150986-ffb8e700-7c70-11e9-9528-016a884e0b88.png)

**Comment by 1991x** [comment] 2019-05-22 11:00
@shue249 it doesn't work.. still error

**Comment by KonstantinGOT** [comment] 2019-05-22 15:38
Is working again!!!

**Comment by KonstantinGOT** [comment] 2019-05-22 15:47
I still cant delete the settings 
![Screen Shot 2019-05-22 at 8 46 56](https://user-images.githubusercontent.com/50840258/58188869-3d684080-7c6e-11e9-92c6-f9ebcbd73bf6.png)

**Comment by KonstantinGOT** [comment] 2019-05-22 16:19
@1991x can you delete settings?

**Comment by 1991x** [comment] 2019-05-22 20:27
@KonstantinGOT no I can't. But at least we can access the page

**Comment by shue249** [comment] 2019-05-22 23:50
@1991x Can you share with us the log file of the plugin for us to take a look.

**Comment by wegee-us** [comment] 2019-05-23 01:01
the same as me, i can't delete the setting. it always shows some problem. i already sent log files and screenshot to your email.  ads_extension_opencart@fb.com

**Comment by wegee-us** [comment] 2019-05-23 01:03
@shue249 please fix it as soon as possible, thanks

**Comment by guilhermeojs** [comment] 2019-05-23 12:48
![51](https://user-images.githubusercontent.com/20118742/58253809-a4095f00-7d3f-11e9-8a1f-2fdb2203bc40.png)

I got the same issue. I don't know if that is related with the fact that my old facebook page got removed and I couldn't unlink the OpenCart beforehand or something else. I've tried uninstalling it but it didn't work. Would you help me?

**Comment by KonstantinGOT** [comment] 2019-05-24 16:35
@shue249  Dear Shue do we have any update?

**Comment by KonstantinGOT** [comment] 2019-05-24 16:37
@guilhermeojs  I believe i have similar story

**Comment by wegee-us** [comment] 2019-05-24 22:26
a lot users have this common problem, i think this is caused by facebook side.

**Comment by KonstantinGOT** [comment] 2019-05-25 01:51
@wegee-us  I actually spoke with FB team  and they said that everything ok on their side

**Comment by wegee-us** [comment] 2019-05-25 04:14
@KonstantinGOT if facebook side is ok, then it should be the extension problem. i think this extension is developed by facebook? or it's third party extension?

**Comment by KonstantinGOT** [comment] 2019-05-25 04:34
@wegee-us  at first i thought that its FB developed  but they use different method of upload of products via pixel.
This is 3rd party and Mr @shue249 already made progress that we been able to access till settings but now awaiting to be able to delete them

**Comment by guilhermeojs** [comment] 2019-05-25 11:33
@KonstantinGOT Did you manage to fix it? I can't access the page to manage settings :/ As my previous facebook page got removed by Facebook I need to change the whole settings to link it with my new Facebook Page in order to add the Messenger plugin as well

**Comment by shue249** [comment] 2019-05-25 16:03
@svremeto , @KonstantinGOT , @1991x , @wegee-us , @Eaglebill , @medeirosrafael , @guilhermeojs 

Thank you for your patience with us. We are working to resolve this problem and we have some information and updates for you.

**Information**
Facebook Ads Extension/Facebook Business extension (the pop up window) and the Facebook for OpenCart (this plugin) is developed by Facebook. I am also an employee of Facebook and I am part of the core team which developed this solution (popup + plugin). I hope this helps to clarify on the ownership of the solution.

**Update**
1. We have rolled out some fixes that helps to solve some of the issues. And we will need your help to help us verify if these fixes are working for you. Because some of you have encounter the same problem but is due to different root causes (and may require different fixes).

2. To do the verification, pls follow the below steps:

  a. Install the version 2.1.8 of our Facebook for OpenCart plugin.

  b. Access the Facebook Ads Extension module using Chrome/Firefox browser. Ensure that you are able to see the Manage Settings button. If you cannot see the button but is stuck at "Checking on Upload status" message, please do a "Empty cache and hard reload" (pls wait for 5 seconds to see if the message goes off).
![image](https://user-images.githubusercontent.com/11957585/58371997-9de6ce80-7f49-11e9-80a6-4c5f9668b1bb.png)

  c. Click on the Manage Settings button. Verify if the Facebook Ads Extension loads properly.

  d. Access the Advanced options -> Delete Settings.

  e. Verify if the "Delete Settings" work.

3. Feedback to us by commenting on this thread if the steps work for you or if you failed at any of the steps. If you are failing at the steps, pls let us know which is the below step you are failing.

  a. Unable to see the Manage Settings button, even though I have Empty cache and hard reload

  b. Unable to see Facebook Ads Extension. It is showing up as "Sorry, something has gone wrong" error messages.

  c. Unable to delete the settings. It is showing up as "Sorry, something went wrong"

4. Depending on your error message, we will feedback to you accordingly.

Again, thank you for your patience and we really want to help you be successful by resolving these problems altogether.

**Comment by guilhermeojs** [comment] 2019-05-25 16:17
Thank you for your time and also for your commitment @shue249 

I have the 2.1.8 version of the plugin installed and I can see the "Manage Settings" button (_it also shows the "Checking on upload status..." and I've also tried emptying cache and hard realoding but it hasn't worked_).

When I click the "Manage Settings" button pops me the "**Sorry, something went wrong**" page(I attached some screenshots here 2 days ago - it shows the exact same thing).

As I've explained above, my company's Facebook page got **deleted** by Facebook and since then I can't access the Settings to change and link it to the new page.

I don't know if it helps, but on the Dashboard it is also showing me this error:
<img width="1470" alt="Screen Shot 2019-05-25 at 13 12 10" src="https://user-images.githubusercontent.com/20118742/58372101-4f0c4b00-7eef-11e9-8f88-2b99591ace06.png">

Thanks again

**Comment by shue249** [comment] 2019-05-25 16:23
@guilhermeojs Thank you for your feedback. Do you have a new Facebook page for your company? If so, there is another option for you to try out.

If you can access your Mysql database, you can delete away the existing Facebook Ads Extension settings and re-do the setup from scratch again. To do that, connect to your Mysql database and run this query.

`delete from setting where code = 'facebook';`

After running this query, try to launch the Manage Setting and see if it works properly.

**Comment by KonstantinGOT** [comment] 2019-05-25 16:26
@shue249 I followed all the steps and still have same problem 
![Screen Shot 2019-05-25 at 9 25 40](https://user-images.githubusercontent.com/50840258/58372206-24aa9580-7ecf-11e9-859d-dd287deb4b40.png)
![Screen Shot 2019-05-25 at 9 25 59](https://user-images.githubusercontent.com/50840258/58372207-27a58600-7ecf-11e9-82da-9f4f564301c6.png)

**Comment by guilhermeojs** [comment] 2019-05-25 16:32
@shue249 
<img width="377" alt="Screen Shot 2019-05-25 at 13 26 37" src="https://user-images.githubusercontent.com/20118742/58372254-61878400-7ef1-11e9-99a9-2908e030b628.png">

It is saying that the table mydatabase.setting doesn't exist.

**Comment by shue249** [comment] 2019-05-25 17:27
@guilhermeojs Did you configure any database "prefix" when you first setup OpenCart? By default, OpenCart will put in the prefix of "oc_" when you first do the setup, which means all your table names will be "oc_xxx". In this case, you can try oc_setting.

![image](https://user-images.githubusercontent.com/11957585/58372796-6ed65a00-7f55-11e9-95ab-21b2fd184d75.png)

**Comment by guilhermeojs** [comment] 2019-05-25 20:46
> @guilhermeojs Did you configure any database "prefix" when you first setup OpenCart? By default, OpenCart will put in the prefix of "oc_" when you first do the setup, which means all your table names will be "oc_xxx". In this case, you can try oc_setting.
> 
> ![image](https://user-images.githubusercontent.com/11957585/58372796-6ed65a00-7f55-11e9-95ab-21b2fd184d75.png)

Damn. It has been a long time since I haven't done something on the DB. It worked.

As soon as i managed to delete the old settings I could access the "Manage Settings" and link it to my new Facebook page. Everything is working just fine now. Thank you for your attention. Keep up the good work.

It would be a great idea to add to the OpenCart Facebook Ads Extension's FAQ how to delete the previous settings manually and start from scratch (I was looking for that everywhere but couldn't find it)

**Comment by 1991x** [comment] 2019-05-25 22:38
Hi @shue249 error message still come out for me
![still error](https://user-images.githubusercontent.com/50851246/58375241-7f4bfc00-7f78-11e9-91cf-827f5cef7856.png)
![still error1](https://user-images.githubusercontent.com/50851246/58375243-8541dd00-7f78-11e9-9aae-68b900473dd5.png)

**Comment by saharock2019** [comment] 2019-05-25 22:50
@shue249 

i still face the error : c. Unable to delete the settings. It is showing up as "Sorry, something went wrong"

thank yoo

**Comment by wegee-us** [comment] 2019-05-26 02:27
@shue249 it works for me to delete setting use MySql Command. But it comes another problem. when i click on get start, then it comes to link the fun page again, but it shows my fun page already connect to another opencart store. I tried to remove connection. then it shows something worng
![QQ截图20190525192527](https://user-images.githubusercontent.com/50933832/58376601-2a31cb00-7f23-11e9-9b23-075f12bfbea6.png)

**Comment by svremeto** [comment] 2019-05-26 08:09
When I go to step "C" and click to Manage Settings i see this window http://prntscr.com/ntg16g as before. 

b. Unable to see Facebook Ads Extension. It is showing up as "Sorry, something has gone wrong" error messages.

**Comment by KonstantinGOT** [comment] 2019-05-26 17:45
@guilhermeojs  did you really managed to delte the settings? if yes please make a screenshot how to do so.
Still cant do it on my end and would like to try manual

**Comment by guilhermeojs** [comment] 2019-05-26 17:47
@KonstantinGOT Yes i did. Just run this on your database and you will be good to go:

delete from setting where code = 'facebook';

**Comment by KonstantinGOT** [comment] 2019-05-26 17:49
@guilhermeojs  not very familiar how to do that. Any possible visual help could be nice to understand.Thank you

**Comment by guilhermeojs** [comment] 2019-05-26 17:51
> @guilhermeojs not very familiar how to do that. Any possible visual help could be nice to understand.Thank you

Just follow these instructions then
https://my.bluehost.com/hosting/help/2153

**Comment by saharock2019** [comment] 2019-05-26 22:30
this method works perfect for me
delete from setting where code = 'facebook';

everything is fine for me now

**Comment by wegee-us** [comment] 2019-05-26 23:20
I still can't connect to the fun page. it show my fun page already connect to another opencart account, i tried click on remove, but it shows something wrong.

**Comment by KonstantinGOT** [comment] 2019-05-27 04:14
@saharock2019  could you share instructions with me with a screenshot please?

**Comment by 1991x** [comment] 2019-05-27 06:06
Is that realy works?

**Comment by KonstantinGOT** [comment] 2019-05-27 15:49
@1991x they say it does but no one actually shares info

**Comment by KonstantinGOT** [comment] 2019-05-27 16:49
@shue249  could you please confirm that people who stated above solution is workable and if yes provide instructions for us

**Comment by shue249** [comment] 2019-05-27 23:29
@wegee-us We are tracking the deletion of existing store connections here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/166

**Comment by shue249** [comment] 2019-05-27 23:33
@KonstantinGOT , @1991x The solution that @guilhermeojs  and @saharock2019 used is a last resort that wiped the existing settings clean from your system to restart the setup again. This solution requires dedicated database knowledge in order to run the command correctly, otherwise it may corrupt your system/data and may not be easy to recover. If you are unsure of how to run the database commands, I will suggest that you do not use this approach. We are working hard to figure out the root cause for your setup.

**Comment by wegee-us** [comment] 2019-05-28 05:49
@shue249 It's working now. thanks

**Comment by wegee-us** [comment] 2019-05-28 05:58
@shue249 Hi, i tried to syn products to facebook, when i click on it, it causes my website down.

**Comment by KonstantinGOT** [comment] 2019-05-28 06:05
@shue249  Shue my man you made it!!!!
Its working again!!!

**Comment by 1991x** [comment] 2019-05-28 09:31
It's working @shue249
I really appreciate your help

**Comment by svremeto** [comment] 2019-05-28 10:49
@shue249 I`m still facing the same issue http://prntscr.com/nud2i8

**Comment by shue249** [comment] 2019-05-28 14:48
@KonstantinGOT , @1991x Glad that this works for you.

**Comment by shue249** [comment] 2019-05-28 14:48
@wegee-us How many products do you have on your website? It takes a while to complete the sync if you have a lot of products

**Comment by shue249** [comment] 2019-05-28 14:54
@Eaglebill , @medeirosrafael Can you try to delete away the settings and see if it works for you

**Comment by wegee-us** [comment] 2019-05-28 22:50
@shue249 we have 1200 products. so it will take website down when first syn ?

**Comment by wegee-us** [comment] 2019-05-28 23:30
@shue249 Hi, we have a problem with our another fun page, that is feed by facebook Pixel. It's feed successfully and import products to facebook catalog automatically when people visit the product page, but we don't know why it only shows 2 products in shop front page, actually we have more than 20 products in catalog. 
![20190528162706](https://user-images.githubusercontent.com/50933832/58518887-dd8a0200-8165-11e9-838d-97fda8ad9688.png)
![20190528162646](https://user-images.githubusercontent.com/50933832/58518888-dfec5c00-8165-11e9-94a0-70cdb46a4c69.png)

**Comment by shue249** [comment] 2019-05-28 23:51
@wegee-us Can you open up a new ticket on your catalog queries and we can follow up on the new ticket.

**Comment by wegee-us** [comment] 2019-05-28 23:51
@shue249 no problem. thanks

**Comment by shue249** [comment] 2019-05-29 23:16
Everyone. We will be closing out this ticket as folks are able to proceed with the deletion operation. Feel free to create a new ticket if you have any further questions.

**Closed by shue249** 2019-05-29 23:16 UTC
