### ISSUE TITLE
displaying incorrect prices, displaying incorrect products

### ISSUE THREAD

**Issue by agendagroup** [facebookincubator/Facebook-For-OpenCart#301] opened 2019-12-04 06:05 UTC
We are using the latest version - Plugin Version: 2.1.13. The client spends a lot on advertising on Facebook but we feel we are losing clicks / conversions due to the errors.

1. the plugin is displaying incorrect prices on Facebook but when you click through to the website from the Ad the price is correct.
2. the plugin is displaying disabled products on Facebook so then a user clicks it and there is no product to display on the website.

example of incorrect price
https://www.glicksfurniture.com.au/stockholm-bookshelf-large
Correct price $549
price on facebook shop $549
price on facebook Ad $599

Example of product displaying in Ads when disabled.
https://www.glicksfurniture.com.au/index.php?route=product/search&search=Tolix%20Bar%20Stool%2065cm%20Xavier%20Pauchard&description=true
Rust colour not available
Ad showing
Tolix Bar Stool 65cm Xavier Pauchard Replica - Rust L... $69

**Comment by shue249** [comment] 2019-12-04 17:08
@agendagroup From your feedback, it looks like the issues come from the ad. Are the ads dynamic ads? If the ads are dynamic ads, are you able to check which is the catalog used for the dynamic ads? The catalog which is setup by the plugin is this - https://www.facebook.com/products/catalogs/2335248106734265/products

1. For the incorrect price, we checked on the Facebook catalog for that product and the price is correctly reflected as $549. Are you able to provide any ad id of that ad, so that we can try to check on why the price is shown as $599 instead of $549. Or if you are able to share any screenshots, that will be helpful too.

![image](https://user-images.githubusercontent.com/11957585/70163611-bc006900-16fa-11ea-9e40-c72ed625111e.png)

2. For the rust product example, we did a search on the product catalog, but wasnt able to locate that particular product. 
![image](https://user-images.githubusercontent.com/11957585/70164038-6ed0c700-16fb-11ea-9eef-d96765537b1f.png)
![image](https://user-images.githubusercontent.com/11957585/70164112-932ca380-16fb-11ea-9d71-14346a6c65d0.png)

From our past experience with other merchants, one of the root cause for this problem is due to a wrong/different catalog used in the ads. I can suggest for you to verify if the catalog used is the correct one.

**Comment by shue249** [comment] 2019-12-09 07:53
@agendagroup Like to check back again on this issue. Do you have the ad id where your client runs the ad and if the ad is a dynamic ads?

**Comment by agendagroup** [comment] 2019-12-09 09:02
We don't have the ad ID but yes they are dynamic ads. However we have
created our own workaround for it which we will monitor. I will come back
to you soon. Thanks.

**Comment by shue249** [comment] 2020-01-02 01:57
@agendagroup We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Closed by shue249** 2020-01-02 01:57 UTC
